src/main/java/com/powsybl/loadflow/open/network/impl/LfBusImpl.java, src/test/java/com/powsybl/loadflow/open/ac/AcLoadFlowVscTest.java
No
Bug fix
SVC active power setpoint is incorrect on one  side of the HVDC line.
SVC active power setpoint is now correct on both sides. …
=> Fix HVDC active power setpoint

appveyor.yml
No
Bug fix
Appveyor Windows build failed because of a limitation to file path size. 
Core build has been move to c:\project to have shorter paths. …
=> Fix Appveyor build (Windows limitation on file path max size)

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworks.java
No
Bug fix.
In case of generator with remote voltage control, there is no check and loadflow compute wrong state.
An exception is thrown to warn users that is it not yet supported.
**Does this PR introduce a breaking change …
=> Throws an exception in case of generator remote voltage

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlow3wtTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowDanglingLineTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTwoBusNetworkTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackTest.java
No
Feature
Distributed slack and reactive limits are not activated by default. We have to add it using a LoadFlowParameter extension.
Distributed slack and reactive limits are now activated by default.
**Does this PR …
=> Activate distributed slack and reactive limits by default

.github/workflows/maven.yml
No
Feature
SonarCloud analysis is run in its own job after build build job have complete.
To save time, SonarCloud analysis is run inside Linux build job. …
=> Run SonarCloud Analysis on same job as build

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlow3wtTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowDanglingLineTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTwoBusNetworkTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/ac/AcloadFlowReactiveLimitsTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackTest.java, src/test/resources/logback-test.xml
No
Bug
To activate/deactivate reactive limits current code rely on a specific parameter in a LoadFlowParameter extension, but there was already an existing parameter for that noGeneratorReactiveLimits.
New code use …
=> Use standard 'noGeneratorReactiveLimits' parameter.

src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java
No
Bug fix
The algorithm to compute a participation factor to distributed slack is different to the one in Hades2.
We have the same algo.
(if any of the questions/checkboxes don't …
=> Fix distributed slack participation algorithm

src/main/java/com/powsybl/openloadflow/network/AbstractFictitiousLfBus.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/MostMeshedSlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlow3wtTest.java
No
Bug fix
Fictitious bus could be created for 3 windings transformers and dangling lines. Unfortunatly, it could happen that one of the fictitious bus is  selected as slack by "most meshed" slack bus selector. 
Fictitious …
=> Exclude fictitious buses from slack bus selection

src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworks.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlLocalRescaleTest.java
The remote voltage control for generators is not yet supported. The loadflow fails.
The target voltage of the generator is rescaled to a value that is coherent with the local nominal voltage.
No calculation.
An approximative calculation.
**Does this PR introduce a breaking change or deprecate an …
=> Remote voltage control not yet supported: rescale to a local control.

src/main/java/com/powsybl/openloadflow/network/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java
No
Bug fix
Static var compensator reactive limits are not taken into account.
We use bmin and bmax to compute reactive limits at nominal voltage. …
=> SVC reactive limits

src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoadingReport.java
Signed-off-by: Anne Tilloy <atilloy@gmail.com>
No.
A bug fix. I have just added a test to discard from the active power control generators which Pmax are close to Infinity. This test seams necessary for computations that comes from a CGMES conversion.  
The compensation fails because factors are equal to zero when they are rescaled by the sum of factors …
=> A generator with maxP equal to Infinity is discarded from active power control.

README.md, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/Transformers.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlow3wtTest.java
Signed-off-by: Anne Tilloy <atilloy@gmail.com>
No, but it could be classified as a bug fix. At that moment, the modeling of three windings transformers in the open load flow through the pi model only allows to have a constant R, X, G and B, and a ratio by leg. 
With this PR, we allow to model at any leg of a three windings transformers a ratio tap changer and a phase tap changer. It means that R, X, G and B depend on the tap …
=> Allow three windings transformers to have a RTC or a PTC at any leg

src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
No
Bug fix.
In case if a branch with x=0 in DC mode, we endup with a by zero division and NaN in the core computation.
Waiting for a real fix, we just throw an exception to stop the computation.
**Does this PR introduce a …
=> Throws an exception in case of x=0 in DC loadflow.

src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/Equation.java, src/main/java/com/powsybl/openloadflow/network/AbstractFictitiousLfBus.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java
No
Bug fix
There is missing validation of generator target voltage. 
Added 3 kinds of validation:
- local: generators connected to same bus with local voltage control
- remote: generators connected to different buses and …
=> Add target voltage consistency validations

src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java
No
Bug fix
This PR fix to issues related to outer loop workflow
- Outer loops are only run one time each. This could lead to unstabilized loop as one outer run might impact previous one. So we need to re-run all outer loops until it is all stabilized.
- In case of Newton-Raphson …
=> Fix outer loop workflow

src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java
No
Bug fix
In reactive limit outer loop, all PV buses could switch PQ (if reactive limit has been reach), leaving the network without any PV bus.
In reactive limit outer loop, we always keep at least one PV bus.
Among those …
=> Avoid switching all buses PV to PQ

.github/workflows/native.yml, src/main/resources/META-INF/native-image/resource-config.json
No
feature
As GraalVM Java8 has a bug that causes a NullPointerException in univocity parser, we switch to GraalVM Java11.
(if any of the questions/checkboxes don't apply, please …
=> Use GraalVM Java11

src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java
OLF diverges on TTG network, but no issue has been written.
The OLF manages a static var compenstor as a generator (with a zero active power). In IIDM, a static var compensator follows a load sign convention for the reactive power set point. 
No sign change is done.
**What is the new behavior (if this …
=> Reactive power set point of IIDM static var compensator follows a load sign convention

src/main/java/com/powsybl/openloadflow/network/MostMeshedSlackBusSelector.java
New method to select the most Meshed slack bus, based on percentile 90 of nominal voltages.
Not an issue but from a real use case divergence of the OLF. In that case, the most meshed bus selector selects a bus that have the greatest nominal voltage (750 kV) but that is not really meshed. The OLF fails to redistribue the slack. 
We avoid from selection really high voltages that …
=> Improve most meshed slack bus selection

src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
No
Bug fix
When a IIDM generator control voltage, targetQ is optional and could be let to NaN.
When adding a generator at LF network creation, some consistency check may change the voltage control status of the generator. In that case a NaN from the targetQ is added to the bus …
=> Fix NaN targetQ issue

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/network/PlausibleValues.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
No
Bug fix
In case of missing reactive key used to distribute reactive power to generators with shared remote voltage bus, we fallback to uniform keys (so same value for all generators).
The problem is that in case of generator with different reactive capabilities (and associated step …
=> Add smarter reactive power keys fallback

src/main/java/com/powsybl/openloadflow/network/MostMeshedSlackBusSelector.java
No but we have a bug here.
The slack bus is selected among observed voltage level and not more among a voltage level does not exist (because it is the result of an interpolation).
We can have as 90th percentile an non observed voltage level.  …
=> Improve the most meshed slack bus selection

pom.xml, src/main/resources/META-INF/native-image/reflect-config.json
No
feature
PowSyBl 3.4.0 has 2 new supported import format: MatPower and PSS/E.
This 2 importers are new supported in GraalVM native image
(if any of the questions/checkboxes don't …
=> Add MatPower and PSS/E importers to GraalVM native image

pom.xml, src/main/java/com/powsybl/openloadflow/network/MostMeshedSlackBusSelector.java
I have performed a test on a classical merged network and on a network merged through the merging view. In some cases, the slack bus selection is not the same in these 2 networks that are functionally identical. 
The selection algorihtm becomes deterministic. 
**What is the new behavior (if this is a …
=> Make the most meshed bus selector deterministic

src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowDanglingLineTest.java
No.
How P1, P2, Q1 and Q2 are linked to IIDM danglingLine.
It seems that bus2 of the LfDanglingLineBranch is linked to the IIDM dangling line terminal.
Now, It is bus1 of the LfDanglingLineBranch is linked to the IIDM dangling line terminal. But I am not sure and I need a review.
**Does this PR …
=> Fix LfDanglingLineBranch P1, P2, Q1 and Q2 

src/main/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadOuterLoop.java
Signed-off-by: Florian Dupuy <florian.dupuy@rte-france.com>
No
Refactor
=> Minor fixes for slack distribution on conform loads

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/util/ParameterConstants.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
Signed-off-by: Jérémy LABOUS <jlabous@silicom.fr>
#147
=> Open loadflow parameters management

src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
Some tests were not included in build check; they were annotated with org.junit.Test instead of org.junit.jupiter.api.Test
No
Bug fix
Some tests not in build check
All tests in build check
This explains why we didn't have a proper coverage for the changes covered by the tests
=> All tests with same junit

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerControlTest.java
No. I have performed some functional tests on IOP dataset. Even if voltage regulation is disabled and phase regulation is disabled, we create discrete voltage and phase control. I have tested OLF on the CGMES files in that context of no discrete regualtion activated. But I have found issues when the regulating terminal does not refer to a bus.
We now check if it refers the …
=> Fixes on discrete controls

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java
No check is done.
Two checks have been added and in case of null controlled branch or open controlled branch, the phase control is not created. …
=> Discard phase control if controlled branch is null or open

src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoadingReport.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java, src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
With this PR, only generator with a zero target P are discarded from the slack distribution. In master branch, generator with negative target P are also discarded. …
=> Fix slack distribution on generation 

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/nr/DcValueVoltageInitializer.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowResult.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTwoBusNetworkTest.java
No.
The LoadFlowResult from powsybl-core is now filled with metrics. …
=> LoadFlowResult management after a DC loadflow

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisParameters.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/util/ParameterConstants.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlLocalRescaleTest.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisTest.java
No.
The default values of  `remoteVoltageControl` is true. The default value of `dcuseTransformerRatio` is true.
I have added `updateFlows` as a parameter that can be changed in the config file, but I am not sure to really understand the need of this parameter.
**What is the new behavior (if this is a …
=> Improve parameters management

src/main/java/com/powsybl/openloadflow/graph/EvenShiloachGraphDecrementalConnectivity.java, src/test/java/com/powsybl/openloadflow/graph/ConnectivityTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java
No
Bug fix
**What is the current behavior?** 
Wrong set of connected components (some connected components missing) in 3 cases:
- tripled (or more) edge between two vertices
- when removing several edges which each create a new connected component
- corner case of removing a "dangling" edge (between a non-null vertex and a null vertex)  
Correct set of connected components
No
=> Even-Shiloach corrections

src/main/java/com/powsybl/openloadflow/graph/EvenShiloachGraphDecrementalConnectivity.java, src/test/java/com/powsybl/openloadflow/graph/ConnectivityTest.java
No
Computation time optimisation
Slow reset when using Even-Shiloach decremental connectivity algorithm
A lot quicker Even-Shiloach implementation: on the test network containing 10k branches, creating LfContingencies from all possible contingencies now takes about 300ms instead of 15s.
No
Helps to a (very) …
=> Even-Shiloach optimisation

src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysis.java
No
Computation time improvement
Looping over all branches of the network to add to the contingency the branches corresponding to the buses which aren't part of the main connected component in post contingency state
Just adding the branches linked to those buses. On the test nework of 10k branches …
=> Security Analysis: avoid looping on all network branches

src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/network/ConnectedComponentNetworkFactory.java
Comments of @floriand-e2r on #199
=> Fix some connectivity issues in sensitivity analysis

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide1DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide2DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
No
Bug fix
When a1 is considered as a variable the rhs, so the part of the equation which has to be moved to right hand side is not correct.
rhs has been fixed …
=> Fix DC equations when a1 is a variable

src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
No
Bug fix
When an IIDM generator is participating to active power slack distribution, with a droop equals to zero, the generator is discarded from slack distribution.
Such a generator is no more discarded but a "standard" …
=> Fix participating generator with zero droop

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/network/HvdcNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
Do not throw an error if we are asking a sensitivity on a component that is not in the network
=> Change disconnected sensitivities management

src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/graph/EvenShiloachGraphDecrementalConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/GraphDecrementalConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/MinimumSpanningTreeGraphDecrementalConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/NaiveGraphDecrementalConnectivity.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java, src/main/java/com/powsybl/openloadflow/network/util/GenerationActionPowerDistributionStep.java, src/main/java/com/powsybl/openloadflow/network/util/LoadActivePowerDistributionStep.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/util/BusState.java, src/test/java/com/powsybl/openloadflow/graph/ConnectivityTest.java
No
Refactor
1. Common code in DcLoadFlowEngine and DcSensitivityAnalysis
2. Redundant calls to connectivity to compute the list of disconnected LfBuses or its complement (and therefore maniplulating the GraphDecrementalConnectivity interface in many methods).
No
=> Refactor dc sensivity analysis

src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/util/BranchState.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
=> Fix bug on DC loadflow when using multiple contingencies with transformers

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/network/FirstSlackBusSelectorParametersReader.java, src/main/java/com/powsybl/openloadflow/network/MostMeshedSlackBusSelectorParametersReader.java, src/main/java/com/powsybl/openloadflow/network/NameSlackBusSelectorParametersReader.java, src/main/java/com/powsybl/openloadflow/util/ParameterConstants.java
No
Bug fix
As far as open-loadflow-default-parameters section is defined in the config.yml, we need to define slackBusSelectorType even if we are interested to just set another parameter, otherwise we get an exception. …
=> Slack bus selector type config should not be mandatory

src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2CurrentMagnitudeEquationTerm.java
=> Fix current magnitude equation for closed branch side 2

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractClosedBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide1DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide2DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/Equation.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/EquationType.java, src/main/java/com/powsybl/openloadflow/equations/Variable.java
No
Bug fix
Variable has a active property which allows a variable considered either as a variable or as a constant in an equation term. The problem is that it is not fully implemented (see the ugly FIXME in Variable.java). By luck when we change the active status of a variable, we always also change the active status of its term, so it works but this is …
=> Remove variable activation

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/util/ParameterConstants.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
N/A
Bug fix
When we run OLF without specific parameters, the parameters are not read from the config.yml file. The default constructor is used.
Load the OLF parameters from config.yml.
The default value for `throwsExceptionInCaseOfSlackDistributionFailure` also changed to `false`. @geofjamg do you …
=> Fix default parameter loading

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/util/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/network/AbstractLoadFlowNetworkFactory.java, src/test/java/com/powsybl/openloadflow/network/HvdcNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
=> Sensitivity analysis: manage contingency on HVDC line

src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
This is a bugfix
Currently, while running a DC sensitivity analysis, the following bug can occur: 
If there are several contingencies, and one of them changes the slack distribution (by losing generators, for example), then it will change the factorStates, and the basecase sensitivity, for all following contingencies. The one that does not change the participation will then be wrong
**What is the new behavior (if this is a …
=> DC sensitivity analysis: bug fix in case of contingency losing a participating element

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/util/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
No
Bug fix
There is 2 not supported cases in sensitivity analysis:
- Branch contingency, open at both sides on base case
- Factor with a branch function, open at one or two sides 
- There is no error and all sensitivities are …
=> Fix disconnected branch issue in sensitivity analysis

src/main/java/com/powsybl/openloadflow/network/LfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java, src/main/java/com/powsybl/openloadflow/network/util/GenerationActionPowerDistributionStep.java, src/main/java/com/powsybl/openloadflow/network/util/GenerationActivePowerDistributionStep.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
Implementation of PROPORTIONAL_TO_GENERATION_P balancetype : 
It reuses GenerationActionPowerDistributionStep class as implementation is the same, only the participation factor is computed differently.
Unsupported balance type test has been replaced by a small test of proportional to generation P balance type.
=> Implementation of PROPORTIONAL_TO_GENERATION_P balancetype

src/main/java/com/powsybl/openloadflow/network/util/GenerationActivePowerDistributionStep.java
- [X ] The commit message follows our guidelines
Following discussion with @annetill we should make sure factor is an absolute value when using proportional_to_generation_p balance type. This did not make it in the original PR.
No absolute value factor for proportional_to_generation_p balancetype.
Factor value is now absolute for proportional_to_generation_p balancetype.
**Does this PR introduce a breaking change or …
=> Use absolute value for balancetype using targetP

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java
Bug fix
When running a voltage sensisitivyt analysis on a disconnected generator, we get a null pointer exception.
The sensitivity factors for that generator are skipped.
=> Fix NPE on disconnected generator, in sensitivity analysis

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
Quck win for https://github.com/powsybl/powsybl-open-loadflow/issues/296
Perf improvement
Buses may be searched for multiple times in the network.
Buses are searched only once and cached.
On the use case described in the issue, the computation time reduces from ~25s to ~8s
=> Sensitivity analysis: add a bus cache to improve input handling perfomance

src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java
Bug
Reference values of voltages are not correctly transformed from per-unit back to kV.
We use nominal voltage to correctly transform back the voltage value.
This is a quick fix, but I guess that those scaling logics could be shared more with other places in the code (loadflow, security analysis).
Also, it's not very safe to have unit tests with nominal voltage all equal to 1 kV, to identify that …
=> Sensitivity analysis: fix voltage reference values for BusVoltagePerTargetV factor

src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/util/ContingencyTripping.java, src/main/java/com/powsybl/openloadflow/util/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowDanglingLineTest.java, src/test/java/com/powsybl/openloadflow/network/DanglingLineFactory.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/util/ContingencyTrippingTest.java, src/test/java/com/powsybl/openloadflow/util/LoadFlowAssert.java
No but we know that the feature is missing.
Now, you can simulate the loss of a dangling line in AC and DC sensitivity analysis. TODO: branch tripping does not support dangling lines. 
It is not supported. 
We loose a line and a fictitious bus. 
**Does this PR introduce a breaking change or …
=> Sensitivity analysis:  support of dangling line contingency

src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/util/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/network/NodeBreakerNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java
Yes, first step to solve issue #289. This doesn't fix that issue, but detects the problematic contingency, gives a warning and does not add it to the propagated contingencies to avoid giving wrong results.
=> Detects coupler when propagating contingency in sensitivity analysis

src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
https://github.com/powsybl/powsybl-core/pull/1727
=> use ServiceLoader.load with the current classloader instead of the context classloader

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStarBus.java, src/main/java/com/powsybl/openloadflow/network/util/GenerationActivePowerDistributionStep.java, src/main/java/com/powsybl/openloadflow/network/util/LoadActivePowerDistributionStep.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/util/ParameterConstants.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java, src/test/java/com/powsybl/openloadflow/network/impl/LfBusImplTest.java, src/test/resources/debug-parameters.json
Use the two new parameters available in powsybl-core isDcUseTransformerRatio and countriesToBalance. The branch for this PR is based on the branch from the PR https://github.com/powsybl/powsybl-open-loadflow/pull/295 to use the compatibility work already done for 4.2.0 release candidate.
Thus it is to be rebased and merged after this PR. …
=> Use new parameters isDcUseTransformerRatio and countriesToBalance

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
=> Don't check non null on debug method toString()

src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
No, it explains the issue. We want to calculate the sensitivity of a PST angle to a monitored branch. The flow on this monitored branch is right in pre-contingency state. We simulate a contingency of this same PST: the flux on the monitored branch on post-contingency state falls to zero.
**What is the …
=> Wrong function reference for BranchFlowPerPSTAngle factor

src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Signed-off-by: yichen88 <tang.yichenyves@gmail.com>
=> Hotfix: use low limit

src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
#327 
In addition, the value of `q1` was not correctly unscaled.
Bug
Static variables are used for the nominal voltages of branches, which leads to using the same nominal voltage to unscale the currents of all branches of the network.
In addition, the value of `q1` was not correctly unscaled. …
=> Fixes in branch results of security analysis

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/PerUnit.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/OperationalLimitsTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java, src/test/java/com/powsybl/openloadflow/network/PerUnitTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java
Refactoring
Per uniting is hard to follow in a few places :
- current values are not per-united with the correct base current value. In consequence, per-united values are not close at all to 1, and some "normalization factor" has been introduced in equations, which has nothing to do there.
- in sensitivity analysis, per-uniting is also mixed in equations, whereas it should only be applied in pre/post processing
Current …
=> Clean up per-uniting

src/main/java/com/powsybl/openloadflow/util/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/network/NodeBreakerNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
Yes, temporary workaround for #333
=> Fix coupler detection bug

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/NonImpedantBranchTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerControlTest.java
No
**What kind of change does this PR introduce?** 
Bug fix
When several buses are controlled in the same non-impedant connected set, in the merged voltage control the controlled bus, the target voltage and the controllers order are not deterministic
In the merged voltage control the controlled bus, the target voltage and the controllers order are deterministic (voltage control kept is the one with the highest voltage control)
No
Issue due to PR #321
=> Fix merge control order

src/main/java/com/powsybl/openloadflow/network/AbstractElement.java, src/main/java/com/powsybl/openloadflow/network/LfElement.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/test/java/com/powsybl/openloadflow/network/UserObjectTest.java
No
Feature
There is no way to extend the LF network to use it for something else that a load flow. 
We can add any additional data to a LF network and to its elements through a user object.
**Does this PR introduce a breaking …
=> User object to extend LF network

src/main/java/com/powsybl/openloadflow/util/NodeBreakerTraverser.java, src/test/java/com/powsybl/openloadflow/util/ContingencyTrippingTest.java
No
Feature
**What is the current behavior?** 
In security analysis, switches are retained even if they are encountered just before encountering a line / a 2wt while propagating the contingency.
Those switches are not retained anymore, leading to a simplified bus breaker view.
No
=> Security analysis: disconnect terminals of isolated end nodes

pom.xml, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/util/NodeBreakerTraverser.java, src/test/resources/debug-network.xiidm
No
powsybl-core 4.3.1
powsybl-core 4.4.0-SNAPSHOT
No
=> Bump powsybl 4.4.0 rc1

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreationParameters.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/ac/nr/DcValueVoltageInitializer.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphsonParameters.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/equations/PreviousValueVoltageInitializer.java, src/main/java/com/powsybl/openloadflow/equations/UniformValueVoltageInitializer.java, src/main/java/com/powsybl/openloadflow/equations/VoltageInitializer.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchWithBreakerIssueTest.java
=> Refactor parameters

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/nr/DefaultNewtonRaphsonStoppingCriteria.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphsonParameters.java, src/test/resources/debug-parameters.json
=> Add max iteration and NR epsilon to parameters

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/VoltageControl.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
No
Refactoring
Shared voltage control is modeled using one PQV bus at controlled bus and (Ngen - 1) reactive distribution equations at all controller buses except one. These equations allows to define reactive power distribution across all voltage controller buses.  
The problem with such …
=> Refactor shared voltage control modelling

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/LfShunt.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfShuntImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java, src/test/resources/n.json
No
Refactoring
We create one equation per IIDM shunt compensator.
We now create one equation for all IIDM shunt compensators connected to same bus. 
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check …
=> Shunt compensator refactoring

src/main/java/com/powsybl/openloadflow/ac/TransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/network/LfShunt.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfShuntImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowShuntTest.java
No.
No SHUNT_B variable are created when the shunt controller is indeed deactivated after creation. For example, if we have already a voltage control at controlled bus or a transformer volatge control at controlled bus. 
**Does this PR …
=> Fix shunt voltage control

src/main/java/com/powsybl/openloadflow/equations/Equation.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
No
feature
There is no way to write an equation system and see inactive equations ands terms.
An option has been added to write into [ ] inactive equations and terms. 
**Does this PR introduce a breaking change or deprecate an …
=> Add option to write inactive equations and terms

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java
No
Bug
There is a check which is working fine with IIDM implementation from core but not for the one of network store. It is because it relies on `Component` equality which is not something required by IIDM API.
Check is done …
=> Fix synchronous component check

src/main/java/com/powsybl/openloadflow/equations/AbstractEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java
No
Bug fix
For wrapped `EquationTerm`, the `this` passed to notification event is not correct: this is the most inner term. 
The most outer term is passed to notification event.
**Does this PR introduce a breaking change or …
=> Fix equation term notification

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java
No
Bug fix
p and q calculated injection is not set correctly for AC system, in case of bus with shunt compensator.
The "empty" criteria to set p and q equations to the bus is not correct if some terms have already been added during bus creation. 
**What is the new behavior (if this is …
=> Create a P and Q bus equations for all buses

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowShuntTest.java
No.
I have met in an IGM (Litgrid) two shunt compensators connected to the same bus but with different regulating terminals (that lead to different buses). In that case, we can solve the equation system because we have more equations than variables. In the case, for example, we have two target V equations for only one B variable.
**What is the current behavior?** *(You can also …
=> Fix: unsupported shunt voltage control

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowShuntTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
Technical debt 
simulShunt load flow parameter is deprecated
shuntCompensatorVoltageControlOn is used instead
**Other …
=> Replace deprecated simulShunt by shuntCompensatorVoltageControlOn

src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
=> Fix load contingency

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java
No
Bug fix
When loadflow, and sensitivity parameters are created using the constructor (so without loading from platform config), extension if not already added is loaded from platform config which is inconsistent with base parameters.
**What is the new behavior (if this is a feature …
=> Fix parameters loading

src/main/java/com/powsybl/openloadflow/ac/PhaseControlOuterLoop.java
=> Improve phase shifter necessary to connectivity detection

src/main/java/com/powsybl/openloadflow/ac/PhaseControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/HvdcConverterStations.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowLccTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
No.
The Hvdc active power set point is applied on converter station that is in rectifier mode, on its AC side. On the inverter AC side, we computes the active power using both loss factors and the losses due to the line itself.
The Hvdc active power set point is applied on converter station that is in …
=> Fix: Hvdc active power setpoint should be interpreted on rectifier AC side

src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphsonResult.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
No
Refactoring
We access the equation system to get bus p and q in Newton Raphson and AC LF. 
We only rely on p and q of LfBus. …
=> Remove equation access in Newtow Raphson

src/main/java/com/powsybl/openloadflow/ac/TransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/AbstractElement.java, src/main/java/com/powsybl/openloadflow/network/LfElement.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/test/java/com/powsybl/openloadflow/network/UserObjectTest.java
No
Bug fix
When transformer voltage control is activated and multiple connected components is activated, the max nominal voltage stored inside outer loop is shared between the different component calculation => consequence is inconsistency/crash for other component calculation. This is …
=> Fix transformer voltage control with multiple components

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
https://github.com/powsybl/powsybl-core/issues/1984
it implements this pr on core : https://github.com/powsybl/powsybl-core/pull/2033
=> Update loadflow provider to get parameters names

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfSwitch.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowBoundaryTest.java, src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchWithBreakerIssueTest.java
No.
This kind of dangling lines are not updated at the network terminal with P and Q values.
P and Q at network terminals are updated.
**Other …
=> Fix: support of non impedant dangling lines

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
No
feature
We cannot cancel an AC security analysis.
AC security analysis can be cancelled
(if any of the …
=> AC security analysis cancellation

src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcValueVoltageInitializer.java, src/main/java/com/powsybl/openloadflow/network/LfContingency.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
No
Bug fix
Multi connected component DC loadflow does not work. Main CC is re-calculated for each of the component.
**Other …
=> Fix multi components DC LF

src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
Bug fix
An exception is thrown when network is invalid (not PV bus for instance) during a security analysis.
No more exception but a computationOk to false in pre contingency result.
**Does this PR introduce a breaking …
=> Fix security analysis behaviour when network is invalid

src/main/java/com/powsybl/openloadflow/network/impl/HvdcConverterStations.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
No.
It changes the sign convention for a sensitivity variable of type `HVDC_LINE_ACTIVE_POWER`, that was totally inverse for both LCCs and VSCs. In the unit tests, we were testing the sensitivity values doing flow before minus flow after, and it seems that it is the contrary.
It is fixed in principle. 
**What is the new behavior (if this is a feature …
=> Fix HVDC set point increase sensitivity convention

src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java
No
Refactoring
We catch `Exception` to detect solver failure
Thanks to https://github.com/powsybl/powsybl-core/pull/1961 and https://github.com/powsybl/powsybl-math-native/pull/21 we can catch a more accurate …
=> Catch MatrixException instead of Exception

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
No. In case of a contingency that involves an element of a GLSK, the computation of sensitivity value and reference flows is wrong. The GLSK has to be updated.
The GLSK is updated and the bus that contains the element is removed. But it leads to an approximation (or an error indeed) in case of two elements connected to the same bus and both part of the GLSK. This is illustrated …
=> DC sensitivity analysis: fix if contingency element is in GLSK

src/main/java/com/powsybl/openloadflow/network/AbstractElement.java, src/main/java/com/powsybl/openloadflow/network/BusDcState.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfContingency.java, src/main/java/com/powsybl/openloadflow/network/LfElement.java, src/main/java/com/powsybl/openloadflow/network/LfGenerator.java, src/main/java/com/powsybl/openloadflow/network/LfLoads.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/LfShunt.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfHvdcImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLoadsImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfShuntImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStarBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfSwitch.java, src/main/java/com/powsybl/openloadflow/network/util/LoadActivePowerDistributionStep.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/network/OriginalIdsTest.java
No
feature
There is no strict equivalence between IIDM elements and Lf Network ones. Some elements like loads and shunts are aggregated and some other one a split (3 windings transformers and dangling lines).
We can get list …
=> Get original ID

src/main/java/com/powsybl/openloadflow/network/LfContingency.java, src/main/java/com/powsybl/openloadflow/network/LfGenerator.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/VoltageControl.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No. Bug fix.
In case of a generator contingency, changing the generator control type is not enough because there is no link with the equation system. The link is between the status of the controller bus and the equation system.
After applying a generator contingency, we have to check that all generators have switch off the voltage control or not. If yes, we …
=> Fix contingency generator for AC computations

src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
No
**What kind of change does this PR introduce?** 
Bug fix (even though the order of branches to remove should not have any impact)
The branches to open set has no determinist order, hence the edges to cut for connectivity computation is in a random order
The branches to open set has a determinist order
No
=> Determinist branchesToOpen order

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/PhaseControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/graph/EvenShiloachGraphDecrementalConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/EvenShiloachGraphDecrementalConnectivityFactory.java, src/main/java/com/powsybl/openloadflow/graph/GraphDecrementalConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/GraphDecrementalConnectivityFactory.java, src/main/java/com/powsybl/openloadflow/graph/MinimumSpanningTreeGraphDecrementalConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/MinimumSpanningTreeGraphDecrementalConnectivityFactory.java, src/main/java/com/powsybl/openloadflow/graph/NaiveGraphDecrementalConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/NaiveGraphDecrementalConnectivityFactory.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java, src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/graph/BridgesTest.java, src/test/java/com/powsybl/openloadflow/graph/ConnectivityTest.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java
No
Bug fix
**What is the current behavior?** 
The edges are not identified, therefore removing several times an edge by calling `connectivity.remove(vertex1, vertex2)` cannot be interpreted as either an error or a removal of two parallel edges.
The decremental connectivity takes an edge as argument when the edge is added and removal is done by giving the edge as argument.
No, internal API
=> Fix decremental connectivity

src/main/java/com/powsybl/openloadflow/ac/PhaseControlOuterLoop.java
=> Clean phase control outer loop code

src/main/java/com/powsybl/openloadflow/network/AbstractPropertyBag.java, src/main/java/com/powsybl/openloadflow/network/PropertyBag.java, src/test/java/com/powsybl/openloadflow/network/PropertyTest.java
No
feature
We cannot remove a property
We can remove a property
(if any of the questions/checkboxes don't …
=> Remove property

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/network/impl/LfBusImplTest.java
Signed-off-by: Etienne LESOT <etienne.lesot@rte-france.com>
#526
=> fix dispatchQ method

src/main/java/com/powsybl/openloadflow/graph/EvenShiloachGraphDecrementalConnectivity.java
No
Bug fix / feature
Main connected component not cached in EvenShiloach implementation of GraphDecrementalConnectivity
Main connected cached lazily in EvenShiloach implementation of GraphDecrementalConnectivity
No
=> Cache main connected component in EvenShiloach connectivity

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
Bug fix : When a multi line contingency breaks connectivity, a disabled line might still be in the main component if both ends are in it.
When a multi line contingency breaks connectivity, a disabled line might still be in the main component if both ends are in it.
When a multi line contingency …
=> Fix AC sensitivity analysis in case of a branch contingency breaking connectivity

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
No
Feature
To configure an injection sensitivity factor we need to provide an injection ID.
We can also instead provide a configured bus ID for a bus/breaker topo or a busbar section ID for a node/breaker topo. 
**Does this PR …
=> Injection sensitivity from bus or busbar section ID

src/main/java/com/powsybl/openloadflow/network/impl/LfBatteryImpl.java
No
Technical debt
We still use deprecated p0 and q0 for batteries.
We now use new methods targetP and targetQ …
=> Replace p0 and q0 of batteries by targetP and targetQ

src/test/java/com/powsybl/openloadflow/ac/AcEquationsTest.java
No
Unit test
A unit test has been added to assert p, q and i equations consistency
=> Assert active power, reactive power and current consistency

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractOpenSide1BranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/AbstractOpenSide2BranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide1ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2ReactiveFlowEquationTerm.java
No
Performance improvement
Less cos(ksi) and sin(ksi) computation
=> Less cos(ski) and sin(ksi) computation

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/PiModel.java, src/main/java/com/powsybl/openloadflow/network/PiModelArray.java, src/main/java/com/powsybl/openloadflow/network/SimplePiModel.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfSwitch.java, src/main/java/com/powsybl/openloadflow/network/impl/OlfBranchResult.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisParameterJsonSerializer.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisParameters.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProviderTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProviderTest.java, src/test/java/com/powsybl/openloadflow/util/LoadFlowAssert.java, src/test/resources/sa-params.json
No
feature
Unit test regarding transformer voltage control  on security analysis are not robust enough because we are not able to to assert post contingency value of the tap.
We can now thanks to a BranchResult extension assert …
=> Improve transformer voltage control unit testing

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/util/ProviderConstants.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProviderTest.java, src/test/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProviderTest.java
No
Feature
We have 3 differents provider names: OpenLoadFlow, OpenSecurityAnalysis and OpenSensitivityAnalysis
All are OpenLoadFlow …
=> Same provider name for LF, SA and Sensi

src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
=> DC Sensitivity analysis: add unit test on IEEE14

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractClosedBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ReactiveFlowEquationTerm.java
No
Refactoring
AC equations have been simplified
=> AC equations simplification

src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcLoadFlowContext.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/equations/AbstractVector.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/EquationVector.java, src/main/java/com/powsybl/openloadflow/equations/TargetVector.java, src/main/java/com/powsybl/openloadflow/equations/Vector.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
=> Refactor equation vector

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/network/LargestGeneratorSlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/LfGenerator.java, src/main/java/com/powsybl/openloadflow/network/SlackBusSelectionMode.java, src/main/java/com/powsybl/openloadflow/network/SlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/network/LargestGeneratorSlackBusSelectorTest.java
No
Feature
A new slack bus selector has been added based on largest generator criteria.
=> Largest generator slack bus selector

src/main/java/com/powsybl/openloadflow/network/impl/ContingencyTripping.java, src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisParameters.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProviderTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/util/sa/ContingencyTrippingTest.java, src/test/resources/sa-params.json
No.
The contingency propagation for AC security analyses is optional, set to true by default. 
(if any of the …
=> AC security analysis: make contingency propagation optional

src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/util/Reports.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/resources/esgTutoReport.txt, src/test/resources/saReport.txt
No
Feature
There is no functional logs for security analysis
Minimal functionnal logs have been added  …
=> Security analysis functional logs

src/main/java/com/powsybl/openloadflow/DefaultOuterLoopConfig.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/ac/IncrementalTransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/PhaseControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/OuterLoopContext.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/OuterLoopContextImpl.java, src/main/java/com/powsybl/openloadflow/equations/TargetVector.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfNetworkListener.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkListener.java, src/main/java/com/powsybl/openloadflow/network/PiModel.java, src/main/java/com/powsybl/openloadflow/network/PiModelArray.java, src/main/java/com/powsybl/openloadflow/network/SimplePiModel.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerControlTest.java, src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java
Not exactly, but the transformer voltage control is a complexe feature. We already have two outerloops, but in some cases, it leads to a divergence or a KLU issue. So, we have decided to try an incremental outerloop.
We add an incremental outerloop. For the moment, at the first resolution, the transformer voltage controls are disabled. The outerloop looks like:
- At each controlled bus, we check if voltage is higher or lower than the …
=> [Transformer voltage control] Incremental transformer outerloop

src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/LfShunt.java, src/main/java/com/powsybl/openloadflow/network/impl/LfShuntImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/Networks.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
No
Bug fix
In DC mode, active power of shunt compensator is at NaN after calculation.
It should be zero. …
=> Fix shunt compensator active power in DC mode

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphsonParameters.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphsonStatus.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowBoundaryTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/resources/debug-parameters.json, src/test/resources/saReport.txt
No
Bug fix
We don't check state validity after NR, and we sometimes update network buses voltage with negative values
A new status UNREALISTIC_STATE has been added
**Does this PR introduce a breaking change or deprecate an …
=> Check NR state validity

src/main/java/com/powsybl/openloadflow/network/util/ZeroImpedanceFlows.java, src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchDisablingTest.java
=> Zero impedance line open at one side NPE

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
=> DC sensi refactoring

src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
=> Miss contingency status in DC sensitivity analysis

src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java
Remove useless reset of variant ID, fixing exception when trying to access an uninitialized variant id from a child thread.
Signed-off-by: Bertrand Rix <bertrand.rix@artelys.com> …
=> Remove reset of variant ID in security and sensitivity analysis

src/main/java/com/powsybl/openloadflow/network/LfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBatteryImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/test/java/com/powsybl/openloadflow/network/impl/LfBusImplTest.java
No
Api cleanup
LfNetwork is passed to some methods of LfGenerator which could lead to inconsistency.
LfNetwork is not passed anymore to some method of LfGenerator …
=> Clean LfGenerator

src/main/java/com/powsybl/openloadflow/sa/LimitViolationManager.java
=> Clean branch limits violation

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java
=> Try to fix AC sensitivity for no impact contingency after normal contingency 

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkList.java, src/main/java/com/powsybl/openloadflow/network/impl/Networks.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sa/LfActionTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java
No
Bug fix
When we create a LF network from an IIDM network in bus/breaker topo, we create it from a temporary variant. The variant is removed just after and created LF network still wraps IIDM objects from removed variants (especially calculated bus which are no more part of the IIDM …
=> Fix network variant removal issue

src/test/java/com/powsybl/openloadflow/ac/LinesWithDifferentNominalVoltagesTest.java, src/test/java/com/powsybl/openloadflow/network/LinesWithDifferentNominalVoltagesNetworkFactory.java
Signed-off-by: Damien Jeandemange <damien.jeandemange@artelys.com>
No change, only test added about lines whose terminals are of different nominal voltage.
This test confirms the option `addRatioToLinesWithDifferentNominalVoltageAtBothEnds` should always be enabled to get correct results in AC NR loadflow.
good behavior :)
unchanged good behavior :)
=> added test for lines with different nominal voltages at both ends

src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcTargetVector.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationType.java, src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchDisablingTest.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
=> Fix DcEquationSystem with disabled non impedant branch

src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java
No
Feature
When computation falied because of unrealistic state, we only have the number of bus withan unrealistic voltage magnitude.
We also have in TRACE mode, all bus ids and voltage magnitude in pu.
**Does this PR …
=> Add unrealistics voltages trace logs

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcLoadFlowContext.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowContext.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/lf/AbstractEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractImpedantLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfSwitch.java, src/main/java/com/powsybl/openloadflow/network/util/ZeroImpedanceFlows.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowMatrixTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
No.
The status of zero impedance branch is defined once, when the LfNetwork is created, in a AC context or in a DC context. So:
- if during the simulation the tap position changes, it does not change this status. Which is not so bad indeed because we don't change the branch equation from an impedant branch equation to a zero impedance one or inversely.
- In case of an …
=> Zero impedance branch management refactoring

src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/Networks.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
No
Refactoring
Some utility methods regarding bus access have been moved to `Networks`.
=> Move bus getters to Networks utility class

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkStateUpdateParameters.java, src/main/java/com/powsybl/openloadflow/network/LfShunt.java, src/main/java/com/powsybl/openloadflow/network/LfStandbyAutomatonShunt.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfShuntImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStarBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfSwitch.java, src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchWithBreakerIssueTest.java
No
Refactoring
Network update methods have too many parameters.
An additionnel object `LfNetworkStateUpdateParameters` has been added to simplify method signature. …
=> Add network update state parameters

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcLoadFlowContext.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowContext.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystemCreator.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowMatrixTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
No
Refactoring
AC and DC equation system creation instead of a static method utility class, use an builder like pattern to store common parameters as attributes and simplify methods signature.
**Other …
=> Refactor equation systems creation

src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/BusState.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
No
Refactoring
switch PV -> PQ counter of reactive limit outer loop is driven by LfBus.setVoltageControlEnabled calls. This is quite dangerous because there is many other reason that could lead to switch of voltage control that PV -> PQ switch (like validation checks).
**What is the new …
=> Refactor PV -> PQ switch counter

src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowShuntTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTwoBusNetworkTest.java
No
Technical debt
We use deprecated API from core.
We don't use anymore deprecated API from core.
(if any of …
=> Update deprecated API usage

src/main/java/com/powsybl/openloadflow/ac/IncrementalTransformerVoltageControlOuterLoop.java
… outer loop
No
Technical debt
Sensitivity calculation in transformer voltage control incremental outer loop, could be simplified as equation is "target_rho = rho" and derivative in respect to rho is 1.
**Other …
=> Simplify sensi calculation on  incremental transformer voltage control

src/main/java/com/powsybl/openloadflow/ac/IncrementalContextData.java, src/main/java/com/powsybl/openloadflow/ac/IncrementalShuntVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/IncrementalTransformerVoltageControlOuterLoop.java
No
Technical debt
updateAllowedDirection is duplicated is transformer et shunt outer loop.
updateAllowedDirection has been moved to incremental context. …
=> Remove updateAllowedDirection method duplication

src/main/java/com/powsybl/openloadflow/DefaultOuterLoopConfig.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java, src/test/resources/debug-parameters.json
No
Feature
We can configure the maximum number of PV/PQ switch count. Default value is 3 instead of 2. 
=> Change default value for max Pq Pv switch and add a parameter

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkStateUpdateParameters.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/HvdcConverterStations.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchWithBreakerIssueTest.java
No
Bug fix
We include line loss even if line is open at one side.
We take 0 as line loss if open at one side. …
=> Fix Hvdc line open at one side

src/main/java/com/powsybl/openloadflow/equations/Equation.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystemIndex.java, src/main/java/com/powsybl/openloadflow/equations/EquationVector.java, src/main/java/com/powsybl/openloadflow/equations/JacobianMatrix.java, src/main/java/com/powsybl/openloadflow/equations/TargetVector.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemIndexTest.java
No
Performance improvement
Based on profiling I tried to solve some performance issues:
- In `EquationSystemIndex`it seems to be faster to copy list of variables et equation in a list after indexing because iterating over a sorted map is slow and we have to do it many times. Also searching and adding to a `HashMap` or `HashSet` is many times faster that in a `TreeMap` or …
=> Various performance improvements

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
No
No
Side is calculated with switch case
Side obtained by getter
No
=> Use SensitivityFunctionType::getSide and SensitivityVariableType::getSide

src/main/java/com/powsybl/openloadflow/ac/AcTargetVector.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationType.java, src/main/java/com/powsybl/openloadflow/ac/nr/PerEquationTypeStoppingCriteria.java, src/main/java/com/powsybl/openloadflow/network/GeneratorVoltageControl.java, src/main/java/com/powsybl/openloadflow/network/ShuntVoltageControl.java, src/main/java/com/powsybl/openloadflow/network/TransformerVoltageControl.java, src/main/java/com/powsybl/openloadflow/network/VoltageControl.java
No
Refactor/Simplify
- BUS_TARGET_V_WITH_SLOPE is removed and replaced by BUS_TARGET_V to be consistent with other voltage control.
- In AC equation system, BUS_TARGET_V is first and always created so that we don't need to create it in each voltage control and create missing at the end.
- In AC equation system, code is shared for the 3 voltage control update (code was …
=> Refactor voltage control equations

pom.xml, src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/network/LfAction.java, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/resources/debug-parameters.json, src/test/resources/sa-params.json
No
Feature
We are based on core alpha1
We are based on core RC1
=> Upgrade to core 5.2.0-RC1

src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Fix contingencies on line disconnected on one side not appearing in post contingency results.
=> Fix contingency on line disconnected at one side

src/main/java/com/powsybl/openloadflow/network/PowerShift.java, src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/sa/LfActionTest.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
No
Bug fix
When a load contingency is simulated in a list with a another switch contingency, it has not the same behavior as if it is simulated alone.
=> Fix no impact load contingency when simulated with a switch contingency

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java, src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
=> Fix disabled voltage control equations

src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Fix pre contingency monitored branch empty in DC Security analysis.
=> Fix empty branch results DC Security analysis pre contingency result.

src/main/java/com/powsybl/openloadflow/ac/outerloop/SecondaryVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
No
Bug fix
Very low voltage controlled sensitivity to set point end up to a double infinity value to the shifted target voltage.
Very low voltage controlled sensitivity are correctly skipped.
=> Fix infinity voltage shift in secondary voltage control outer loop

src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java, src/main/java/com/powsybl/openloadflow/network/util/GenerationActivePowerDistributionStep.java, src/main/java/com/powsybl/openloadflow/network/util/LoadActivePowerDistributionStep.java, src/main/java/com/powsybl/openloadflow/network/util/ParticipatingElement.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java
No
Bug fix
Slack distribution: Exception is thown although option is set to not throw in case of slack distribution failure.
Happens if network has right from start no element of requested type.
=> Exception: No more <elementType> participating to slack distribution

src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
No
Bug fix
When an equation is removed, corresponding indexed terms are not cleaned. 
=> Clean indexed terms when removing an equation

src/main/java/com/powsybl/openloadflow/AcLoadFlowFromCache.java, src/main/java/com/powsybl/openloadflow/NetworkCache.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineGenerator.java, src/main/java/com/powsybl/openloadflow/util/Reports.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowWithCachingTest.java
No
Bug fix
In fast restart mode, when re-running a LF without any network change we get a FAILED status. 
We get a CONVERGED status (in really this should be a ALREADY_CONVERGED)
=> Fix already converged case in fast restart mode

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/nr/NewtonRaphsonStoppingCriteriaTest.java, src/test/java/com/powsybl/openloadflow/network/BoundaryFactory.java
No
Bug fix
With reactive limits enabled, bus Q balance may be non zero in the case of a bus forced to remain PV.
fixed bus Q balance
No
Note that the solution produced would leave generators outside reactive limits. We may want to revise this strategy in another PR (e.g. make this behavior optional, or flag the component as non converged).
=> Fix generators update after forcing a bus to remain PV

src/main/java/com/powsybl/openloadflow/network/impl/LfLoadImpl.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java
Fix constant power factor when distributing slack on loads
Slack is not correctly distributed on some types of loads, when only the variableReactivePower is not 0.
Slack will always be correctly distributed
=> Fix calculated load Q when distributed slack on loads with constant power factor

src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
No
Bug fix
When dcUseTransformerRatio option is to true, the post contingency reference flows are not consistent with the one calculated from a DC LF. This ratio seems not to have been taken into account in the alpha calculation that allow us to calculate post contingence reference flow from pre contingency reference flow.
=> Fix dcUseTransformerRatio not taken into account in DC sensi

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/dc/DcValueVoltageInitializer.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystemCreationParameters.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystemCreator.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowMatrixTest.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
=> Clean/fix phase control parameter in DC computations

src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
No
Bug fix
DC and AC sensi analysis do not take into account the network slack bus extension.
DC and AC sensi analysis take into account the network slack bus extension.
=> Get slack from network in sensi analysis

src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide1DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide2DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
No
Performance improvement
For reference flow calculation, we need to calculate pre-contingency state using DcLoadFlowEngine. The problem with current implementation is that we integrate the calculated state into the state vector and update the network which in consequence invalidate the Jacobian which will be needed to be recalculated (identically to before invalidation...).
We use a special version of the DcLoadFlowEngine that do not  update the state vector nor the network. Flow are calculated from equation terme using a special …
=> Improve performance of reference flow calculation in a DC sensi analysis

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
#832 
Bug fix
throws NullPointerException if controlledBranch is in another component
remote reactive power control is disabled, warning is issued.
No
=> Fix NPE in remote reactive power control

src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisContingenciesTest.java
No
Bug fix
When computing the post contingency reference flow of a line which is in series with another line which is itself the contingency, we would expected to post contingency active power flow to be zero. Instead we have a very small value. 
=> Fix small reference flow values instead of strict zero

src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
=> BusResults after security analysis is not exhaustive

src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java
Empty list instead of null for bbsIds (and make final).
=> Fix null BusBarSections ids 

src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java, src/test/java/com/powsybl/openloadflow/sa/AbstractOpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisContingenciesTest.java
No
Cleanup
We sometimes use loadflow with sparse matrix (and native code) in test
We only need to use dense matrix because small cases and full Java implementation
=> Use dense matrix factory everywhere in tests

src/main/java/com/powsybl/openloadflow/network/GeneratorVoltageControl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoadingReport.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
No
Feature
Each time we have a generator with a zero reactive key, we log an error.
We only warn about the number of generator with a zero reactive key, detailed logs are only at trace level.
=> Reduce the number of zero reactive key log error

src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
No
Feature
We write a synthetic log when a bus that is to a reactive limit need to update its q because reactive limit has changed.
=> Add log to reactive limit outer loop when limit has changed

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisContingenciesTest.java
When we have an invalid factor, we write the results for pre-contingency state only. If the factor is also associated to a contingency, nothing is written for this contingency. But... we have now specific contingency context, so it means that for these factors, the pre contingency state is not asked. But we provide results for it. 
For the moment, nothing. Two solutions:
- We output all results.
- We output pre contingency state for contingency context none or all, and for a specific contingency only if contingency context specific. …
=> Fix invalid factors in specific contingency context

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowWithCachingTest.java
No
Bug fix
In fast restart mode, when we re-run a LF and that no calculation was needed we reset state in IIDM but never re-update it.
In that case we do not reset not update state.
=> Network update fix in case of fast restart

src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/sa/AbstractNetworkResult.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
When monitoring three windings transformer with a disconnected leg, the SA result production fails with NPE. Probably just missing a null check. I added a test to show the issue, I will add a fix soon.
=> Fix three windings transformer with disconnected leg monitoring

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoadingReport.java
No
Feature
We have one warning log for each transformer voltage control discarded because controller branch is open.
This is now only traces and one synthetic warn has been added.
=> Synthetic discarded transformer voltage control log

src/main/java/com/powsybl/openloadflow/network/impl/OlfThreeWindingsTransformerResult.java
Make constructor public for OlfThreeWindingsTransformerResult like for OlfBranchResult instead of package private.
No
Bug fix
missing constructor from #875
added constructor to OlfThreeWindingsTransformerResult 
No
See #875
=> OlfThreeWindingsTransformerResult constructor public

src/main/java/com/powsybl/openloadflow/network/LfContingency.java, src/test/java/com/powsybl/openloadflow/network/FourBusNetworkFactory.java, src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Bug fix
Reactive keys for voltage control are not being updated correctly in SA after a generator is lost
=> Fix update reactive keys for voltage control

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java
No
Bug fix
We get a NPE when HVDC emulation is activated and we have a VSC or LCC converter station without a HVDC line.
=> Fix NPE on VSC without a HVDC line

src/main/java/com/powsybl/openloadflow/network/impl/LfShuntImpl.java
No
Bug fix
When b and g of a shunt is reinit from IIDM values, network notification are not sent.
=> Fix shunt b and g reinit notification

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractClosedBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchI1xFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ShuntCompensatorActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ShuntCompensatorReactiveFlowEquationTerm.java
No
Refactoring
Some methods around equation terms are now public for easier reuse.
=> Make some equation term methods public

src/main/java/com/powsybl/openloadflow/network/ReactivePowerDispatchMode.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java, src/test/java/com/powsybl/openloadflow/network/impl/LfBusImplTest.java
Bug fix
Reactive power is always equally split between generators on a bus controlling the reactive power on a branch. Thus, ignoring the reactive keys. 
The reactive keys will not only work for splitting the reactive power between different buses but also for different generators on the same bus.
**Other …
=> Fix sharing of reactive power with for multiple generators with ReactivePowerControl

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/ac/solver/DefaultNewtonRaphsonStoppingCriteria.java, src/main/java/com/powsybl/openloadflow/ac/solver/NewtonRaphsonStoppingCriteria.java, src/main/java/com/powsybl/openloadflow/ac/solver/PerEquationTypeStoppingCriteria.java, src/test/java/com/powsybl/openloadflow/ac/MultipleSlackBusesTest.java, src/test/java/com/powsybl/openloadflow/ac/solver/NewtonRaphsonStoppingCriteriaTest.java
No
BugFix
AC NR loadflow PowsyblException "Unknown equation term" when using 1/ multiple slack buses with 2/ PerEquationTypeStoppingCriteria
cause: missing BUS_DISTR_SLACK_P in PerEquationTypeStoppingCriteria
bugfix:
- BUS_DISTR_SLACK_P correctly taken into account using maxActivePowerMismatch threshold
- any other equation term use newtonRaphsonConvEpsPerEq threshold
No
=> Fix PerEquationTypeStoppingCriteria

src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
Remote reactive power target of generators is not held on zero impedance branches.
Target is now held even if branch has null impedance
=> Generator remote reactive power control on non impedant branches

src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfSwitch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfTieLineBranch.java, src/main/java/com/powsybl/openloadflow/sa/AbstractNetworkResult.java, src/main/java/com/powsybl/openloadflow/sa/PostContingencyNetworkResult.java, src/main/java/com/powsybl/openloadflow/sa/PreContingencyNetworkResult.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Yes, issue #972 
A proposal, even if I am not really satisfied on my proposal. When a tie line id or at least one of the dangling line ids are in the input state monitor, we output the three branch results.  
=> Support paired dangling lines ids in state monitors

src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/NonImpedantBranchTest.java, src/test/java/com/powsybl/openloadflow/network/NonImpedantNetworkFactory.java, src/test/java/com/powsybl/openloadflow/network/ZeroImpedanceNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
Yes, in PR #955 issue found during unit testing.
A line is reconnected temporary for loading only if it is disconnected at both side. If one side is connected, the line is in the LF network. In main branch, a line connected tagged as to be closed in an action is processed as disconnected. The result is a big bug in the topology restauration just after loading.  
**What changes might users need to make …
=> Fix terminals connection action

src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/Networks.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowGeneratorTest.java, src/test/java/com/powsybl/openloadflow/network/FourBusNetworkFactory.java, src/test/resources/n2.json
No.
Double.NaN as Q in the terminal of a generator that has been discarded from voltage control.
=> Bug in reactive power dispatching 

src/main/java/com/powsybl/openloadflow/ac/outerloop/DistributedSlackOuterLoop.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
No
Bug fix
With parameter `slackDistributionFailureBehavior` set to `DISTRIBUTE_ON_REFERENCE_GENERATOR`, the reported distributed active power in the LoadFlowResult's component results is wrong.
Fixed the DistributedSlackOuterLoop to properly account slack active power distributed to reference generator
The feature `slackDistributionFailureBehavior` `DISTRIBUTE_ON_REFERENCE_GENERATOR` was originally developed in #959.
=> Fix ComponentResult distributed active power

src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java
… in the hvdc line
- [X ] The commit message follows our guidelines
No
Explicit tests to check that a VSC in voltage control station holds tension even if no active power is flowing through the HVDC line.
VSC stations behave as they should (tension is maintained even if P=0) but there is no explicit test to verify this.
VSC stations are holding tensions because the test check that Pmin < epsilon but for VSC stations Pmin is large but negative.
The tests prevent that a change in this condition breaks the VSC desired behviour. 
No …
=> Add unit test with VSC voltage control and targetP = 0

src/main/java/com/powsybl/openloadflow/network/impl/Networks.java, src/test/java/com/powsybl/openloadflow/network/FourBusNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
Bug fix
When restoring the initial topology in SA, we try to close switches/branches in all LfNetworks. When we have more than 1 LfNetwork, the code crashes.
We will be able to restore the initial topology in SA with multiple SCs.
=> Fix restoreInitialTopology in SA with multiple SCs

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractHvdcAcEmulationFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/HvdcAcEmulationSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/HvdcAcEmulationSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/network/LfHvdc.java, src/main/java/com/powsybl/openloadflow/network/impl/LfHvdcImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/EquationsTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java
Take into account active power limits of HVDC in AC emulations
They can be defined by
maxP in the HVDC line
Or in the  HvdcOperatorActivePowerRange extension that provides a limit in each direction
Limits are ignored in AC Emulation
Limits are honoured.
If P0+KdeltaPhi out of range, P is capped to a bound of the range?
- [ X] No
=> Honnor HVDCOperatorActivePowerRange as well as Pmax of hvdcLine in AC emulation

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
No
(minor) Bugfix
`debugDir` String parameter metadata declares an empty list as possible values, although any value should be allowed. GUI relying on parameter metadata would be confused by this empty list.
`debugDir` String parameter metadata declares a null list as possible values (= any string value).
=> Fix debugDir parameter possible values

src/main/java/com/powsybl/openloadflow/network/LfAction.java, src/test/java/com/powsybl/openloadflow/sa/LfActionTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
Bug fix (i guess ?)
Powsybl Generator actions are all converted to relative power actions, applied on top of the power after the contingency (and potential slack distribution)
If the action is absolute, the absolute targetP is directly set, regardless of the potential changes due to slack after contingency …
=> Absolute generator action ignores post-contingency slack

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java, src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java
No
Debatable Bug fix vs. feature
We only support remote reactive power control on line and 2 windings transformer
We additionally support remote reactive power control on 3 windings transformer
=> Support generator remote reactive control on 3 windings transformer terminal

src/main/java/com/powsybl/openloadflow/network/impl/LfBatteryImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowBatteryTest.java
No, only notice on two buses that Kirchoff law is violated on RTE network.
Fix that because update state was not taken into account for a battery with voltage control.
=> Fix Battery update state after voltage control

src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisContingenciesTest.java
No.
In a DC sensitivity analysis, we have a connectivity analysis to determine the breaking connectivity elements. The method to determine them first select candidates for connectivity break, but some of them can be removed because there are not breaking connectivity. If we have some of them, we have to update the connectivity with only breaking connectivity elements.
**What changes might users need …
=> Connectivity data in DC sensitivity analysis

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java
#913 
Bugfix
SVC when OFF result in NaN values for terminal P&Q
SVC when OFF result in 0.0 MW/Mvar values for terminal P&Q
=> Fixed Static VAR Compensator OFF mode having NaN P and Q results

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/test/java/com/powsybl/openloadflow/ac/AcloadFlowReactiveLimitsTest.java
Signed-off-by: Damien Jeandemange <damien.jeandemange@artelys.com
No
Bugfix
Reactive power dispatch is not accounting for plausible reactive power range.
In case of:
- a generator with Qmin;Qmax = [0.0; 0.0]
- with voltage regulation enabled
- and reactive limits disabled in parameters,
this results in incorrect (zero) Mvar result on the generator's terminal, and sum of bus reactive flows is not zero.
(Especially visible e.g. on Entso-e "RealGrid" test case).
Reactive power dispatch is accounting for plausible reactive power range …
=> Fix Q dispatch not accounting for plausible reactive power range

src/main/java/com/powsybl/openloadflow/equations/TargetVector.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Yes, https://github.com/powsybl/pypowsybl/issues/758
Nothing for the moment, just a unit test that shows the bug. In DC security analysis only, equations can have rhs. If the rhs of these equations changed, because in contingency for example, but it could be a tap position change of a P0 change for HVDC, we have to invalidate the DC target vector. It is not the case on main branch. 
We have the issue just today because it was hidden before through the sensitivity analysis API.   
**Does this PR introduce a breaking change or …
=> DC security analysis: RHS is not invalidated

src/main/java/com/powsybl/openloadflow/sa/AbstractNetworkResult.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
Bug fix
When configuring a dangling line ID in the state monitor, we get an exception because of duplicated network results. 
We do not have duplicated results anymore.
=> Fix state monitor duplicated results with tie lines

docs/conf.py, docs/loadflow/parameters.md
No
Doc fix & update
`reactiveRangeCheckMode` is incorrectly saying that range at Pmax and Pmin is checked.
Accurate description of what `reactiveRangeCheckMode` actually does and better description of what is "reactive range".
=> Fix and improve reactiveRangeCheckMode parameter documentation

src/main/java/com/powsybl/openloadflow/sensi/ConnectivityBreakAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
No. We have an optimization in the DC sensitivity analysis that groups contingencies if they include the lost of the same element necessary to connectivity. This optimisation is really small compared to the difficulties it adds to the code and its maintainability. 
=> Remove grouping by element necessary to connectivity

src/main/java/com/powsybl/openloadflow/sensi/ConnectivityBreakAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
No.
The sensitivity factors are removed form connectivity break analysis.
Factor holders are used to verify if the contingencies have associated sensitivity factors.
This check is now done in DC sensitivity analysis.
=> Remove sensitivity factors in connectivity break analysis

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowReportTest.java
No
Bug fix
In AC loadflow, network is updated on the connected component even if no calculation has been made. This leads for instance to some incorrect values on islands with no active generators (p0 and q0 set to p and q on loads).
In AC loadflow, network is only updated is the result is successful, similarly to DC loadflow.
=> AC loadflow: no network update on NO_CALCULATION

src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/WoodburyEngine.java
The method runDcLoadFlow is in DC sensitivity analysis
The method is now an utility method in WoodburyEngine class
=> Move runDcLoadFlow from DC sensitivity analysis to DcLoadFlowEngine

src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
The method is in DC sensitivity analysis
The method is now an utility method in PropagatedContingency class
=> Move cleanContingencies from DC sensitivity analysis to utility method

src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java
No
Bugfix
Corner case which wasn't handled in #1041: in case the reference generator is not in the "participating elements", we still see the unwanted hysteresis effect.
Correct slack distribution on generators.
=> Fix slack distribution if reference generator is not participating element

src/main/java/com/powsybl/openloadflow/NetworkCache.java, src/main/java/com/powsybl/openloadflow/network/LfAction.java, src/main/java/com/powsybl/openloadflow/network/LfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBatteryImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/util/ParticipatingElement.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowWithCachingTest.java
No
Feature
We are able to change target p of generators and batteries with fast restart
=> Fast restart for active power target change

src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowBoundaryTest.java, src/test/java/com/powsybl/openloadflow/ac/solver/NewtonRaphsonStoppingCriteriaTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
Bug fix
Unpaired dangling lines are simulated with shunt admittance split between network side and boundary side, which is not compliant with iIDM model.
Unpaired dangling lines are simulated with shunt admittance on network side only in compliance with iIDM model.
See also https://github.com/powsybl/powsybl-core/pull/3169 on similar subject
=> Fix unpaired DanglingLine simulated with split shunt admittance

src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/SelectedSlackBus.java, src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java, src/test/java/com/powsybl/openloadflow/network/TwoBusNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
updateSlackBusesAndReferenceBus implements a slack bus selection algorithm using an exclude list of buses in excludedSlackBuses.
Some time a bus is selected because it is the one and only with the highest voltage. If this bus is also in the exclude list then we have no solution available.
I changed a bit the algorithm by filtering the bus list with the exclude list before applying the selection algorithm so it is not able to base its selection on buses that will not be available anyway.
To illustrate the bug surfaced on a small network similar to this : 
B1(vl 150) ---- B2(vl 150) ---- B3 (vl380)
A contingency cut the line between B2 and B3. B3 is  then put in the exclude listof selectable slack bus because it is no longer in the main …
=> Fix SA exception "No slack bus for network"

src/main/java/com/powsybl/openloadflow/network/impl/HvdcConverterStations.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/Networks.java, src/test/java/com/powsybl/openloadflow/ac/SecondaryVoltageControlTest.java, src/test/java/com/powsybl/openloadflow/network/impl/HvdcConverterStationsTest.java, src/test/java/com/powsybl/openloadflow/network/impl/NetworksTest.java
No
Bug fix.
Secondary voltage control does not work with generators using remote voltage control.
The issue was just some wrong checks at network loading. I rewrote theses checks and logs additionnal infos.
=> Fix secondary voltage control in case of generators with remote volage control

src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/util/Reports.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisContingenciesTest.java, src/test/resources/saReport.txt, src/test/resources/saReportOperatorStrategyNoVoltageControl.txt
No
Bug fix
- Exception occurring when island is a single bus with a generator on voltage control, and the contingency removes the generator (`PowsyblException: Expected to have same number of equations (2) and variables (1)`)
- Also I think something should be clarified about what happens if a contingency leaves the network without any bus under voltage control, I think it is strange to have the NR converging, why not mathematically speaking, but from a physical point of view this is surprising. Today we rely on unrealistic state check, but I think this is not correct.
**What is the new …
=> Fix Security Analysis in case of no more voltage regulated bus

src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/WoodburyEngine.java
No
This PR follows this PR: https://github.com/powsybl/powsybl-open-loadflow/pull/1109
Some variable names and comments have been modified to ensure a better maintanability of the code
=> Refactor DC Woodbury

src/main/java/com/powsybl/openloadflow/equations/JacobianMatrix.java, src/test/java/com/powsybl/openloadflow/equations/LUDecompositionTest.java
No
Bug Fix
In some rare cases, the NR fails with a MatrixException - klu_refactor error KLU_SINGULAR
This happens when the Jacobian Matrix uptes the LU in incremental mode.  
But, in those cases, if the LU matrix is updated in non incremental mode the operation succeeds.
At this time, this has only be seen in large model and it has not been possible to isolate a simple case with the issue. 
When the Jacobian updates occurs in incremental mode, if the LU update fails a second try is attempted in non incremental mode.
**Does this PR …
=> Retry LU decomposition if incremental mode fails

src/main/java/com/powsybl/openloadflow/ac/AcTargetVector.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java, src/test/java/com/powsybl/openloadflow/ac/MultipleSlackBusesTest.java
Bug fix
When using multi slack, loads or gens on slack buses are ignored because value for P in target vector is 0. This results in the existing injections to be "mangled"/reported in the slack injection incorrectly.
Take P injection into account on slack buses equations for the multi slack case
=> Fix injections ignored on slack buses when using multi slacks

src/main/java/com/powsybl/openloadflow/network/AbstractLfNetworkLoaderPostProcessor.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkLoaderPostProcessor.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
No
Feature
`LfNetworkLoaderPostProcessor` notifies on element-per-element creation, but no global 'LfNetwork has been loaded' event is available, which could be useful for more complex post-processing tasks.
Add new  'LfNetwork has been loaded' event to `LfNetworkLoaderPostProcessor`.
=> Add LfNetworkLoaderPostProcessor.onLfNetworkLoaded event

src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/WoodburyEngine.java
No.
DC LF with modified target vector is moved in WoodburyEngine following dicussion in #1095.
The method is in DcLoadFlowEngine.
The method is in WoodburyEngine.
=> Refactor DC load flow with modified target vector in WoodburyEngine

src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java
No.
The distinction between post contingency result computation is refactored in Woodbury DC Security Analysis.
In current behavior, code is duplicated. The only difference between the two calculations is the method used to calculate post contingency states (conditionned by post contingency connectivity result).
The code is mutualized. 
**What changes might users need to make in their application due …
=> Refactor separation of post contingency calculations in Woodbury DC Security Analysis

src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfLoad.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/HvdcConverterStations.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLoadImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/Networks.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/network/HvdcNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java, src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisContingenciesTest.java
No
In https://github.com/powsybl/powsybl-open-loadflow/pull/965 a simple criteria was added to detect an HVDC disconnection on one side : 
A station is isolated if its merged bus is not connected to any other bus neither to a load or a group.
This criteria was meant to detect quickly contingencies that disconnect a line, while allowing simple models where one side is merely simplified as a group or a load.
But in real networks it happens that a fictive load is added to a station.
This fix considers that if an HVDC's stations contains only fictive loads it is still considered isolated.
**NOTE that this criteria for automatic …
=> fictive load on isolated bus keeps hvdc isolated

src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/network/ConnectedComponentNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
Bugfix
Handle properly secondary synchronous component from main connected component in SA
Secondary synchronous component of main CC were ignored by the network selection on which we computed sa.
All component are now handled correctly and in a way similar as the load flow 👍 
MAIN component mode will compute SA on main connected and all its synchronous component.
ALL component mode will compute SA on all connected component and all synchronous component. 
=> Fix secondary synchronous components in main CC not computed in SA

src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide1DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide2DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/Equation.java, src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/EquationVector.java, src/main/java/com/powsybl/openloadflow/equations/InjectionDerivable.java, src/main/java/com/powsybl/openloadflow/network/util/ZeroImpedanceFlows.java, src/main/java/com/powsybl/openloadflow/util/Derivable.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java
This is another approach to fix #1137
Clairify the equation model:
evallhs = target - rhs
and
eval = evallhs - rhs
evallhs is used to solve equations
eval is used to get the equation or term quantity
Errors seen with non impedant branches in DC near a PST or an HVDC in AC emulation with P0 non null.
Potental inconsitenscies each time a non null RHS is used
Error fixed
- [ X No
=> Refacto lhs

src/main/java/com/powsybl/openloadflow/ac/outerloop/DistributedSlackOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java, src/test/java/com/powsybl/openloadflow/network/DistributedSlackNetworkFactory.java
No
Bug fix
<del>Regression introduced in the #1148 refactoring.</del>
The root problem is not really the refactoring, actually the code before the refactor was hiding a bug. The real problem is the computation of the `movedBuses` indicator in `ActivePowerDistribution`.
In the following situation:
- the slack power to be distributed is small but above threshold, e.g. 0.15 MW vs. 0.10 MW threshold,
- and there are many elements over which we distribute the mismatch (e.g. 1000 elements)
then each element moves by only 0.000015 MW, below epsilon threshold. Consequently `ActivePowerDistribution` …
=> Fix slack distribution outerloop incorrect stable status

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfTieLineBranch.java
No
Performance issue
Security analysis profiling shows that we spend a lot of time accessing limit violation from the IIDM network. 
There is an issue with the way LfLimit creation from IIDM limits and caching is done. The IIDM access is done at each call even if LfLimit has already been created and cached.
I guess this issue (already ever present) is more visible since we have added operationnal limits in IIDM because we now have an indirection when accessing an operational limit group (using the current limit group and going though …
=> Fix performance issue when accessing loading limits from IIDM

docs/.readthedocs.yaml
Documentation configuration update: allows to download readthedocs documentation in pdf format.
See https://github.com/powsybl/powsybl-core/pull/3253
=> Enable download of documentation in pdf format

src/main/java/com/powsybl/openloadflow/ac/AcTargetVector.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java, src/test/java/com/powsybl/openloadflow/ac/MultipleSlackBusesTest.java
No
A previous PR (https://github.com/powsybl/powsybl-open-loadflow/pull/1116) fixes injections that are ignored in slack buses when using multiple slacks. But actually, the problem is just partially solved because injections are still ignored when being in **the first** slack. This is due to the distribution equations.
Example with 3 slack buses
Before the previous fix (#1116) we had these distribution equation between slacks :
slack_p2 - slack_p1 = 0
slack_p3 - slack_p1 = 0
After the previous fix (#1116) we had these distribution equation between slacks :
slack_p2 - slack_p1 = target_p2 …
=> Fix injections ignored on first slack bus when using multiple slacks

src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLoadImpl.java
No
Perfs improvement
When profiling a DC security analysis we get 2.8% if the time spent in calculating bus active power. Generation part is alreadu cached bu not load part.
After caching also the load part, we get twice faster.
After using a traditionnal loop instead of a stream, we get 0;
**Other …
=> Load active power target caching

docs/loadflow/parameters.md, src/main/java/com/powsybl/openloadflow/ac/outerloop/SecondaryVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/GeneratorVoltageControl.java, src/main/java/com/powsybl/openloadflow/network/LfSecondaryVoltageControl.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/SecondaryVoltageControlTest.java
No
Bug fix
Secondary voltage control outer failed in case a zone has generators belonging to a shared remote control.   
All generators of a secondary voltage control, have local voltage control.
=> Fix secondary voltage control in case of generator remote voltage control

src/main/java/com/powsybl/openloadflow/network/impl/ContingencyTripping.java, src/test/java/com/powsybl/openloadflow/util/sa/ContingencyTrippingTest.java
No
Bug fix
The tripping corresponding to a bbs contingency with no propagation adds the traversed terminals in the neigbours list.
The tripping corresponding to a bbs contingency with no propagation adds the visited terminals in the traversed terminals set.
=> Fix busbar section minimal tripping

src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisTest.java
No
Misleading exception message was thrown when load flow fails in AC sensi analysis. A correction is done to this message.
When running an AC sensitivity analysis, if the first load flow fails because of UNSTABLE outer loop status, a PowsyblException is thrown with message : "Load flow ended with status CONVERGED"
A correct exception message is thrown depending on Load flow result.
=> Modified exception message when initial LF fails in AC Sensi

docs/loadflow/parameters.md
No
Documentation of newtonRaphsonStoppingCriteriaType = UNIFORM_CRITERIA was wrong
Documentation of UNIFORM_CRITERIA mentions that all mismatches must be lower than a threshold which is wrong.
Documentation of UNIFORM_CRITERIA mentions that the criteria is :
$\sqrt {mismatch_1^2 + mismatch_2^2 + ... + mismatch_n^2} < \sqrt{n * newtonRaphsonConvEpsPerEq^2}$
=> Fix doc for newtonRaphsonStoppingCriteriaType=UNIFORM_CRITERIA

src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java
No
Today, mutli-thread security analysis does not support operator strategy,
because each thread verifies that a contincency exists for every action. But each thread has only a sublist of contingencies so
this fatally leads to errors.
With this PR, the operator strategy checks are performed before running the treads. So that:
- exceptions thrown for missing action ids are sent to the launching thread
- matching contingencies for operator strategy contingency contexts are performed before the contingency partitioning
=>  Support operator strategies in MT

src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
no
Bug fix
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
the nodes gotten in violationLocation are not the ones fromthe nodebreakerview of the bus
=> fix voltage violation location

src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
No.
The usage of the method `matrixCopyValues` is replaced for the equivalent method implemented [here](https://github.com/powsybl/powsybl-core/pull/3216). 
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
=> Clean matrixCopyValues method in DC Sensitivity Analysis.

pom.xml, src/main/java/com/powsybl/openloadflow/network/action/LfActionUtils.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/util/Reports.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/resources/saMtReport.txt
**NOTE**: needs this PR to build: https://github.com/powsybl/powsybl-core/pull/3303
- [ X ] The commit message follows our guidelines
- [ X ] Tests for the changes have been added (for bug fixes / features)
Some issues are reported in [#1167](https://github.com/powsybl/powsybl-open-loadflow/issues/1167)
There are some issues with Security Analysis in MT:
* Reports contain duplicated entries for network loading and precontingency run
* PostContingency results are split in different node (one per thread)
* Operator Strategies are not supported (an exception is thrown because a contingency is not in the partition of a given …
=> Fix SA reports in MT 

src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/test/java/com/powsybl/openloadflow/sa/WoodburyDcSecurityAnalysisWithActionsTest.java
No
In DC the active power mismatch is computer on all bus whether they are enabled or disabled.
This leads to wrong computations in Security Analysis if the lost network contains unbalanced loads and generators.
**Note** that in general the slack distribution is a loss of time in DC security analysis because it was initially made extactly based on the contingency propagation. So the DC engine performs a useless iteration on all buses in SA.
Slack distribution in DC security analysis (default mode) is long each time a unbalanced part of the network is lost.
**What is the new behavior (if this …
=> fix double slack distribution in SA DC

src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java
No
A test fails in https://github.com/powsybl/powsybl-open-loadflow/pull/1174 because the NR stopping criteria are larger thatn the epsilon used for result comparisons. 
This test ensures stopping criteria are small enough so that the test is independent of the computation order.
Test assertions not relevant because comparison precision is smaller than algorithm stopping criteria.
Test assertion precision consitent with algorithm stopping criteria. The tests is independant of the NR implementation.
**Does this PR introduce a breaking …
=> Adapt engine stopping criteria to test precision

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
the following parameters are not read from a config file:
- `forceTargetQInReactiveLimits`
- `fictitiousGeneratorVoltageControlCheckMode`
- `voltageRemoteControlRobustMode`
- read the param value from the config file
- add a test to check that all parameters are read
- add other parameters that were not handled in update
=> Fix parameters not read from platform config

src/main/java/com/powsybl/openloadflow/network/LfContingency.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
- [X ] The commit message follows our guidelines
- [X ] Tests for the changes have been added (for bug fixes / features)
No
Bug fix:
In node breaker mode, loads and generators on a bus affected by a contingency are counted twice
Lost loads and generators are not counted a second time if they belong to a lost bus
- [X ] No
=> In Connectivity Report do not count twice lost loads and generators that are on a contingency bus

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/sa/LimitViolationManager.java
No, but the development is based on the collaborative work of #1169 , aiming to improve the performance of the fast DC SA. 
The access to branch limits is refactored, for better performances.
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
The branch limits are stored in Maps, indexed by `LimitType`. 
There is a list of limits for each `LimitType`. Some method references are also replaced by lambdas.
With this refactoring, the time spent on detection of limit violations is …
=> Refactor access to branch limits when detecting limit violations

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
When a generator attached to a bus is disabled, exclude it from Q limit computations.
Disabled generators are counted in Q limits.
Disabled generators are excluded from Q limits.
=> Filter disabled generators when computing bus Q limits

pom.xml
No
Bug fix
Jacoco report is not generated.
Jacoco report is generated.
#1225 set command line arguments for the `maven-surefire-plugin`, but it ignored potential previous arguments. By doing this, it ignored the `-Pjacoco` option used to generate the test coverage report.
The current …
=> Fix jacoco report generation

src/test/java/com/powsybl/openloadflow/network/BusBreakerNetworkFactory.java, src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java, src/test/java/com/powsybl/openloadflow/network/MetrixTutorialSixBusesSecurityAnalysisFactory.java, src/test/java/com/powsybl/openloadflow/sa/AbstractOpenSecurityAnalysisTest.java
Fixes #1254 
Refacto to no longer use deprecated methods.
=> Replace use of deprecated OperationalLimitsGroup limits creation methods

README.md, pom.xml
Bump powsybl-core to published version 6.8.1
The powsybl-core dependency references a version with known vulenrabily from dependency
https://mvnrepository.com/artifact/com.powsybl/powsybl-core/6.8.0
OpenLoadFlow references powsyb-core 6.8.1 that addresses the issue.
=> Bump powsybl-core to 6.8.1

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisTest.java
This PR resolves issue #1270 
It is now possible to compute the sensitivity to a battery inkection by specifying the battery ID.
Before, you could only specify the battery bus ID.
If a sensibility analysis is run with a battery ID provided as an injection variable, OpenLoadFlow throws a PowsyblException with message "Injection '<batteryId>' not found" 
If a sensibility analysis is run with a battery ID with a battery ID provided as in injection variable, the corresponding bus is found and the sensitivities are computed correcty. …
=> Sensitivity analysis: allow to specify a battery ID as an injection variable id

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/test/java/com/powsybl/openloadflow/ac/AcloadFlowReactiveLimitsTest.java
No
Bug fix
Q dispatch uses an internal hardcoded threshold of 1e-3 pu @ 100 MVA (hence 0.1 MVAr) when dispatching Q.
In some situations this may leave a bus imbalance above requested convergence threshold.
Issue was observed on real data for a generator with reactive limits at +/- 0.1 MVAr. Depending on NR solution path and solution precision we end up with either  Q being dispatched (then KCL check OK), or not dispatched (KCL check failing).
- Test case added, with a generator at +/- 0.05 MVAr limit so that numerical precision …
=> Fix Q dispatch not meeting requested reactive power mismatch threshold
