powsybl/powsybl-open-loadflow

src/main/java/com/powsybl/loadflow/open/network/impl/LfBusImpl.java, src/test/java/com/powsybl/loadflow/open/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/loadflow/open/ac/AcloadFlowReactiveLimitsTest.java, src/test/java/com/powsybl/loadflow/open/ac/DistributedSlackTest.java
No
Bug fix
Generator reactive power is incorrectly updated in IIDM network at the end of the loadflow.
Generator reactive power is now correct.
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check …
=> Fix generator reactive power

pom.xml
No
Security issue fix
We use apache commons compress 1.17 which has security vulnerabilities.
We now use version 1.19 which is safe. …
=> Update apache commons compress version (security issue)

.travis.yml, README.md, appveyor.yml, pom.xml
No
Feature
Open loadflow depends on core snapshot version. 
To prepare a future release of open load flow we need to depend on a core release (3.0.0).  …
=> Use PowSyBl Core release (3.0.0)

src/main/java/com/powsybl/loadflow/open/network/impl/LfLeg1Branch.java, src/main/java/com/powsybl/loadflow/open/network/impl/LfLeg2or3Branch.java
No
Bug fix
In case of 3 windings transformer open at one of the terminal, we get a NullPointerException …
=> Fix open 3 windings transformers issue

pom.xml, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlow3wtTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowDanglingLineTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTwoBusNetworkTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/ac/AcloadFlowReactiveLimitsTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackTest.java, src/test/java/com/powsybl/openloadflow/ac/nr/NewtonRaphsonParametersTest.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowMatrixTest.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationTest.java, src/test/java/com/powsybl/openloadflow/equations/VariableTest.java, src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java, src/test/java/com/powsybl/openloadflow/network/NameSlackBusSelectorTest.java, src/test/java/com/powsybl/openloadflow/network/PerUnitTest.java, src/test/java/com/powsybl/openloadflow/network/impl/LfNetworksTest.java, src/test/java/com/powsybl/openloadflow/util/LoadFlowAssert.java
No
Technical debt.
Unit tests are based on JUnit4.
Unit tests are based on JUnit5.
(if any of the …
=> Migrate to JUnit5

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
No
Bug fix.
`LoadFlowProvider` implementation name is OpenLoadflow but should be OpenLoadFlow.
`LoadFlowProvider` implementation name is now OpenLoadFlow. …
=> Fix LoadFlowProvider name

pom.xml
N/A
Prepare the first release of powsybl-open-loadflow
=> Prepare release 0.1.0

src/main/java/com/powsybl/openloadflow/ac/AcLoadFlowLogger.java, src/main/java/com/powsybl/openloadflow/ac/AcLoadFlowProfiler.java, src/main/java/com/powsybl/openloadflow/ac/nr/AcLoadFlowObserver.java, src/main/java/com/powsybl/openloadflow/ac/nr/DefaultAcLoadFlowObserver.java, src/main/java/com/powsybl/openloadflow/ac/nr/MultipleAcLoadFlowObserver.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java
No
Feature
In debug mode, 5 biggest mismatches  are  displayed to help debugging
(if any of the …
=> Log biggest mismatches

src/main/java/com/powsybl/openloadflow/network/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/MostMeshedSlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworks.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStarBus.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowDanglingLineTest.java
No
Feature
LF model has been improved and it is now possible to get branches connected to a bus.
(if any of …
=> Get branches from a bus

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide1ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ShuntCompensatorReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide1DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide2DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/AbstractEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/AbstractTargetEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/Equation.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/EquationType.java, src/main/java/com/powsybl/openloadflow/equations/Variable.java, src/main/java/com/powsybl/openloadflow/equations/VariableType.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
No
Feature
It is now possible to write an equation system for debugging purpose.
=> Write equation system for debug

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java
=> Refactoring

src/main/java/com/powsybl/openloadflow/network/AbstractFictitiousBranch.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLeg1Branch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLeg2or3Branch.java, src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchTest.java, src/test/java/com/powsybl/openloadflow/network/NonImpedantBranchNetworkFactory.java
#31
Bug fix
Non impedant branches case is not handled. There is even not at least error message or exception, so consequently loadflow badly fail with NaN in the calculation.  
An exception is  throw, waiting for correctly …
=> Throws an exception in case of non impedant branch

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/nr/DcValueVoltageInitializer.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcLoadFlowResult.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowResult.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkLoader.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/Networks.java, src/test/java/com/powsybl/openloadflow/ac/AcloadFlowReactiveLimitsTest.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowMatrixTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java, src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java, src/test/java/com/powsybl/openloadflow/network/NameSlackBusSelectorTest.java, src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
No
Refactoring
LF network is not totally decoupled from IIDM network.
LfNetworkLoader has been added to allow multiple network format loading and allow more easily integration of other network model into this load flow.
**Does …
=> Refactor network loading

pom.xml, src/main/java-templates/com/powsybl/openloadflow/util/PowsyblOpenLoadFlowVersion.java
No
Feature
There is no way to known at runtime which version of the code has been used for build.
Powsybl Version plugin has been added. …
=> Add PowSyBl repo version infos

src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/AbstractFictitiousBranch.java, src/main/java/com/powsybl/openloadflow/network/AbstractFictitiousLfBus.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoadingReport.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStarBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/test/java/com/powsybl/openloadflow/network/NameSlackBusSelectorTest.java
No
Refactoring
Network loading code could be simplified. Is also need to be refactored to allow loading post prcessing (like bus merging is case of low impedance branches). Warning logs should also be compacted.
=> Network loading refactoring

README.md
- [ x] Docs have been added / updated (for bug fixes / features)
No.
It could be a roadmap but it is more a way to guide the futur external collaborations or contributions. 
Nothing.
**Other …
=> Add a contributing section in the README file

pom.xml, src/test/java/com/powsybl/openloadflow/network/DistributedSlackNetworkFactory.java, src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
No
feature
Open loadflow depends on PowSyBl Core 3.1.0
Open loadflow depends on PowSyBl Core 3.2.0
(if …
=> Switch to PowSyBl Core 3.2.0

pom.xml
No
feature
Project is based on parent pom v1
Project is based on parent pom v3
(if any of the …
=> Use parent pom v3

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
Signed-off-by: Anne Tilloy <atilloy@gmail.com>
No, but a null pointer exception appears if we try to access to the bus Id if the bus is null.
(if any of the questions/checkboxes …
=> Check if controlled and controller buses are null

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcLoadFlowResult.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTwoBusNetworkTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java
No
feature
There is no support for multiple synchronous components .
Multiple synchronous components are support, one loadflow is ran on each synchronous component.
**Does this PR introduce a breaking change or deprecate an …
=> Multiple synchronous components support

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreationParameters.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/equations/Equation.java
No
Refactoring
To prepare further developpment AcEquationSystemCreationParameters is added.
=> Add AcEquationSystemCreationParameters

src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowLccTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java
Adapt unit tests.
LossFactor is considered without unit.
LossFactor is considered as a percentage.
(if any of the …
=> The lossFactor is a percentage (bug fix).

pom.xml, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
No
Bug fix
PowSyBl version is not generated anymore
pom.xml has been fixed to generation version again …
=> Fix version generation

src/main/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/AbstractFictitiousLfBus.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java, src/test/java/com/powsybl/openloadflow/network/DistributedSlackNetworkFactory.java
No
Buf fix
Negative loads are discarded from network. 
Negative loads are discarded from slack distribution
**Other …
=> Fix distributed stack on load

pom.xml, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
* New design of extensions for CoordinatedReactiveControl.
(if any of the questions/checkboxes don't apply, please delete …
=> Update to powsybl-core 3.3.0

pom.xml, src/main/resources-native-image/logback.xml, src/main/resources/META-INF/native-image/resource-config.json
No
feature
There is no logback config included in native image
There is a logback config included in native image
**Other …
=> Add logback.xml to native image

README.md
=> Update the roadmap of the README.md.

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
No
Bug fix
In case of divergence we update low impedance branches. 
We only update in case of convergence.
**Other …
=> Update low impedance branch flows only in case of convergence

src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java
- [] Tests for the changes have been added (for bug fixes / features)
No
Bug fix
In case of phase tap changer on a 3 windings transformer leg, we throw an exception.
We don't throw an exception anymore but we log an error. …
=> Replace exception by log for 3wt with phase shifter

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/PiModel.java, src/main/java/com/powsybl/openloadflow/network/PiModelArray.java, src/main/java/com/powsybl/openloadflow/network/SimplePiModel.java, src/test/java/com/powsybl/openloadflow/NonImpedantBranchTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java
No
Bug fix
Low impedance branches are replaced by a coupler at equation level.
We have 2 modes to deal with low impedance branches:
- as before by replacing by a coupler 
- by cutting impedance
**Does this PR introduce a …
=> Add low impedance cut option

src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java
=> Replace exception by error for remote phase shifter not implemented

src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java
No
Bug fix
controlled has been used in several places instead of controller. 
(if any of the …
=> Fix controller/controlled typo

.github/workflows/native.yml, pom.xml, src/main/resources/META-INF/native-image/jni-config.json, src/main/resources/META-INF/native-image/reflect-config.json, src/main/resources/META-INF/native-image/resource-config.json
No
feature
CGMES importer has been added to GraalVM native image
=> Add CGMES importer to GraalVM native image

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ShuntCompensatorReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide1DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide2DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/AbstractTargetEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/Equation.java, src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java
No
Bug fix
In the equation API, RHS should not depend on variable.
=> Refactoring equation rhs

src/test/java/com/powsybl/openloadflow/NonImpedantBranchTest.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlow3wtTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowDanglingLineTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowLccTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTwoBusNetworkTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/ac/AcloadFlowReactiveLimitsTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlLocalRescaleTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java, src/test/java/com/powsybl/openloadflow/ac/SwitchPqPvTest.java, src/test/java/com/powsybl/openloadflow/ac/nr/NewtonRaphsonParametersTest.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowMatrixTest.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationTest.java, src/test/java/com/powsybl/openloadflow/equations/VariableTest.java, src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java, src/test/java/com/powsybl/openloadflow/network/NameSlackBusSelectorTest.java, src/test/java/com/powsybl/openloadflow/network/PerUnitTest.java, src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
No
Bug fix
There is a lot of recent Sonar issues in test packages because of a default rules change.
All Sonar issues in test packages have been fixed …
=> Fix Sonar issues in test

pom.xml, src/main/java/com/powsybl/openloadflow/ac/equations/AbstractBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/test/java/com/powsybl/openloadflow/NonImpedantBranchTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
No
Bug fix
When we have 2 parallel non impedant branches, we end up with a "klu singular issue".
(if any …
=> Parallel non impedant branch support

pom.xml
=> Bump 0.5.0-SNAPSHOT

README.md
No
docs
README.md has been to updated to v0.4.0 release.
=> Update readme to 0.4.0 release

src/main/java/com/powsybl/openloadflow/ac/AcLoadFlowProfiler.java, src/main/java/com/powsybl/openloadflow/ac/nr/AcLoadFlowObserver.java, src/main/java/com/powsybl/openloadflow/ac/nr/DefaultAcLoadFlowObserver.java, src/main/java/com/powsybl/openloadflow/ac/nr/MultipleAcLoadFlowObserver.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
=> Detailed profiling

pom.xml, src/main/java/com/powsybl/openloadflow/network/impl/LfShuntImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlow3wtTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java, src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java
No
feature
We are based on powsybl core 3.4.0
We are based on powsybl core 3.5.0
=> Migrate 350

src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowDanglingLineTest.java
no
Bug fix
Starting from powsybl core 3.5.0, dangling line have voltage regulation capability. This PR add support to this new feature. 
(if any of the questions/checkboxes don't …
=> Dangling line with generation support

README.md
No
feature
We move to 0.6.0-SNAPSHOT following 0.5.0 release
README.md has been updated
=> Bump 0.6.0-SNAPSHOT

pom.xml
=> Fix snapshot version number ?

src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java
No
feature
In LF network branches are not only indexed by num bu also by id.
=> Index branches by id

src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/EquationType.java, src/main/java/com/powsybl/openloadflow/equations/SubjectType.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
No
feature
Equations are indexed by subject (branch or bus) and num.
=> Index equations by subject

src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkLoader.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkLoadingParameters.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java
No
refactoring
Add LfNetworkLoadingParameters to group network loading parameters
=> Refactoring, add LfNetworkLoadingParameters

src/main/java/com/powsybl/openloadflow/graph/EvenShiloachGraphDecrementalConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/MinimumSpanningTreeGraphDecrementalConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/NaiveGraphDecrementalConnectivity.java
=> Code smells corrections

pom.xml, src/main/java/com/powsybl/openloadflow/graph/NaiveGraphDecrementalConnectivity.java, src/test/java/com/powsybl/openloadflow/graph/BridgesTest.java
Updating to the latest Java 8 jgraphT version.
No
LIbrary update
powsybl core 3.5.0
jgrapht 1.0.1
powsybl core 3.6.0
jgrapht 1.4.0 …
=> Updating PowSyBl Core 3.6.0 and jgrapht library

README.md, pom.xml
No
feature
We switch du 0.7.0-SNAPSHOT as 0.6.0 has been released
=> Bump 0.7.0-SNAPSHOT and update README.md

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/network/FirstSlackBusSelectorParametersReaderImpl.java, src/main/java/com/powsybl/openloadflow/network/MostMeshedSlackBusSelectorParametersReaderImpl.java, src/main/java/com/powsybl/openloadflow/network/NameSlackBusSelectorParametersReaderImpl.java, src/main/java/com/powsybl/openloadflow/network/SlackBusSelectorParametersReader.java, src/main/java/com/powsybl/openloadflow/network/impl/MostMeshedSlackBusSelectorParametersReaderImpl.java, src/main/java/com/powsybl/openloadflow/util/ParameterConstants.java, src/main/resources/META-INF/native-image/resource-config.json, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/resources/configFirstSlackBusSelector.yml, src/test/resources/configMostMeshedSlackBusSelector.yml, src/test/resources/configNameSlackBusSelector.yml
Signed-off-by: Thomas ADAM <tadam@silicom.fr>
#147
=> Add SlackBusSelector to config file as open loadflow parameter

README.md, pom.xml
No
powsybl-core 3.6.0
powsybl-core 3.7.1
=> Upgrade to powsybl-core 3.7.1

README.md, pom.xml, src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/util/ParameterConstants.java, src/test/java/com/powsybl/openloadflow/NonImpedantBranchTest.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlow3wtTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowDanglingLineTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowLccTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTwoBusNetworkTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/ac/AcloadFlowReactiveLimitsTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java, src/test/java/com/powsybl/openloadflow/ac/SwitchPqPvTest.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Signed-off-by: Thomas ADAM <tadam@silicom.fr>
No
Feature
Using OpenLoadFlow parameters dc, DistributedSlack & BalanceType
Using LoadFlow parameters dc, DistributedSlack & BalanceType
**Other …
=> Use loadflow parameters dc, DistributedSlack & BalanceType (powsybl-3.7.1)

README.md, pom.xml
No
Version update
0.7.0-SNAPSHOT version
0.7.0 then 0.8.0-SNAPSHOT
No
=> Release v0.7.0

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfSwitch.java
No
Bug fix
Phase regulation done when updating state even if not enabled in LoadFlowParameter
Phase regulation done only if enabled
No
=> Phase control corrections

pom.xml
=> Bump to powsybl-core 3.8.0-RC1

.github/workflows/native.yml, pom.xml, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/resources/META-INF/native-image/jni-config.json, src/main/resources/META-INF/native-image/reflect-config.json, src/main/resources/META-INF/native-image/resource-config.json
=> GraalVM 20.0.3

pom.xml
No
powsybl-core 3.8.0-RC1
powsybl-core 3.8.0
No
=> Bump to powsybl-core 3.8.0

README.md, pom.xml
No
Version update
0.8.0-SNAPSHOT version
0.8.0 then 0.9.0-SNAPSHOT
No
=> Release v0.8.0

.github/workflows/native.yml
No
feature
We use GraalVM 20.3.0
We use GraalVM 21.0.0 …
=> GraalVM 21.0.0

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/network/ConnectedComponentNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
=> GLSK support and sensitivity n minus k

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowLccTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/network/HvdcNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
=> Sensitivity analysis: allow injections on LCC and VSC station

pom.xml, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowMatrixTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
No
feature
Java8
Java11
**Does this PR introduce a breaking change or deprecate an API?** Yes
=> Upgrade to java 11

src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/util/BranchTripping.java, src/main/java/com/powsybl/openloadflow/util/ContingencyContext.java, src/main/java/com/powsybl/openloadflow/util/NodeBreakerTraverser.java, src/main/java/com/powsybl/openloadflow/util/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/network/NodeBreakerNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/util/BranchTrippingTest.java
=> Use branch tripping for contingencies in sensitivity analysis

pom.xml, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
=> Migrate to PowSyBl 4.0.0

pom.xml
No
Library update
powsybl-core 4.0.0
powsybl-core 4.0.1
No
=> Migrate to powsybl-core 4.0.1

pom.xml
No
Version update
0.9.0-SNAPSHOT version
0.9.0 then 0.10.0-SNAPSHOT
No
=> Release v0.9.0

src/main/java/com/powsybl/openloadflow/ac/DistributedSlackOuterLoop.java, src/test/java/com/powsybl/openloadflow/NonImpedantBranchTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowDanglingLineTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java
=> Increase slack active power distribution threshold

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
=> Only update network state in case of convergence

src/main/java/com/powsybl/openloadflow/network/impl/LfStarBus.java
=> Fix star bus nominal voltage

src/test/java/com/powsybl/openloadflow/OperationalLimitsTest.java
With this PR, the load flow on the three windings transformer factory converges. I have changed the slack bus.
Without, max iteration is reached, no solution is found. …
=> Fix tests with the three windings transformer factory

src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
=> Create a result even if no calculation

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
=> Print activated outer loops

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
=> Do not show warning if no factor has been skipped

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractClosedBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide1DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/ClosedBranchSide2DcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/AbstractEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java, src/main/java/com/powsybl/openloadflow/network/AbstractFictitiousLfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfShunt.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfShuntImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfSwitch.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/OperationalLimitsTest.java, src/test/java/com/powsybl/openloadflow/network/impl/LfSwitchTest.java
=> Refactor network and equation link

pom.xml
=> Upgrade Mockito version

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java
=> Fix old TODO in AC equation system

src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisFactory.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java
=> Use fast connected connectivity algo everywhere

pom.xml
No
powsybl-core 4.0.1
powsybl-core 4.1.0
No
=> Bump to powsybl-core 4.1.0

src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
No
**What kind of change does this PR introduce?** 
Bug fix
=> Revert #223 (Fix participating generator with zero droop)

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/SensitivityFactorReaderAdapter.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java, src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java
=> BusVoltagePerTargetV sensitivity factor support

pom.xml
No
Version update
0.10.0-SNAPSHOT version
0.10.0 then 0.11.0-SNAPSHOT
No
=> Release v0.10.0

pom.xml
No
Feature
Dependency/version management inherited from powsybl-core needs to be repeated in open-loadflow pom.xml
Dependency/version management inherited from powsybl-core.
No
=> Import powsybl-core pom

src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlLocalRescaleTest.java, src/test/java/com/powsybl/openloadflow/graph/BridgesTest.java
No
Bug fix
There is a few JUnit 4 checks in unit tests.
All have been replaced by JUnit 5 checks
(if any …
=> Replace JUnit checks 4 by 5

src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
=> Fix sensi replay

pom.xml
No
powsybl-core 4.2.0-RC1
powsybl-core 4.2.0
No
=> Bump powsybl-core to 4.2.0

pom.xml
No
Version update
0.11.0-SNAPSHOT version
0.11.0 then 0.12.0-SNAPSHOT
No
=> Release v0.11.0

src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/test/java/com/powsybl/openloadflow/network/LfBusNumBugTest.java
=> Fix LF network bus numbering bug

src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java, src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java
No.
Some treatments are done only of regulations are active such as creating phase controls, creating discrete controls or creating switches.
We create everything every time.
(if …
=> Simple load flow performances

pom.xml
No
powsybl-core 4.3.0-RC1
powsybl-core 4.3.1
No
=> Bump powsybl-core to 4.3.1

pom.xml
No
Version update
0.12.0-SNAPSHOT version
0.12.0 then 0.13.0-SNAPSHOT
No
=> Release v0.12.0

src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStarBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
=> Refactoring: fix code duplication

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/DefaultOuterLoopConfig.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/OuterLoopConfig.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java
No
Feature
Outer loops list is hard coded and outer loop can only be activated/deactivated using parameters
We can replace the outer loop list using an external plugin configuration. This allows to have custom internal …
=> Outer loop configuration plugin support

pom.xml
No
powsybl-core 4.4.0-RC1
powsybl-core 4.4.0
No
=> Bump to powsybl-core 4.4.0

pom.xml
No
Version update
0.13.0-SNAPSHOT version
0.13.0 then 0.14.0-SNAPSHOT
No
=> Release v0.13.0

src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
=> Fix failing unit test

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystemPostProcessor.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkLoaderPostProcessor.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
No
feature
When adding custom outer loops, it is often necessary to also customize equation system.
An equation system post processor has been added. …
=> Equation system post processor

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java
=> Fix A1 and R1 derivative calculation

src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java
No
Bug fix
Double nan check is incorrect
Double.isNan has to be used
(if any of the questions/checkboxes …
=> Fix double nan check

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/equations/TargetVector.java, src/main/java/com/powsybl/openloadflow/network/AbstractElement.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfNetworkListener.java, src/main/java/com/powsybl/openloadflow/network/DiscretePhaseControl.java, src/main/java/com/powsybl/openloadflow/network/DiscreteVoltageControl.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfElement.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkListener.java, src/main/java/com/powsybl/openloadflow/network/PiModelArray.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLoads.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
=> Various refactoring

pom.xml, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/util/NodeBreakerTraverser.java, src/main/java/com/powsybl/openloadflow/util/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/OperationalLimitsTest.java
No
Dependency version update
powsybl-core 4.4.0
powsybl-core 4.5.0
No
=> Bump powsybl-core to 4.5.0

pom.xml
No
Version update
0.14.0-SNAPSHOT version
0.14.0 then 0.15.0-SNAPSHOT
No
Do not squash the commits!
=> Release v0.14.0

src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
Bug fix
Sparse implementation is used by a few tests.
Dense implementation is used in all unit tests.
(if …
=> Fix matrix implementation in unit tests

src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/equations/Equation.java, src/test/java/com/powsybl/openloadflow/equations/EquationTest.java
=> Print element ID with mismatches

src/main/java/com/powsybl/openloadflow/network/FirstSlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/MostMeshedSlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/NameSlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/NetworkSlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/SelectedSlackBus.java, src/main/java/com/powsybl/openloadflow/network/SlackBusSelector.java
No
feature
We don't log selected slack bus
We log selected slack and also selection method
(if any of the …
=> Log slack bus ID and selection method

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/network/NameSlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/SlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java, src/test/resources/configNameSlackBusSelector.yml, src/test/resources/debug-parameters.json
=> Remove slack bus selection hack when multiple components

README.md, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java
=> Fix predefined results for AC sensitivity analysis in post contingency run

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ShuntCompensatorReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/AbstractBranchEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/AbstractEquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java
=> Refactor branch equation term

src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStarBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java, src/main/java/com/powsybl/openloadflow/network/util/PreviousValueVoltageInitializer.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
=> Refactor bus calculated voltage

src/main/java/com/powsybl/openloadflow/ac/VoltageMagnitudeInitializer.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/equations/Equation.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/Variable.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/equations/EquationTest.java, src/test/java/com/powsybl/openloadflow/equations/VariableTest.java
=> Rename Variable and Equation getNum to getElementNum

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java
=> Fix isDeriveA1

pom.xml, src/test/resources/debug-parameters.json
=> Bump to powsybl-core 4.6.0-RC1

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationType.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcVariableType.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationType.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcVariableType.java, src/main/java/com/powsybl/openloadflow/equations/Equation.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowMatrixTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationTest.java
=> Rename variable and equation type

src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/JacobianMatrix.java
No
feature
In order to help to find performance bottlenecks, additional logs with time have been added.
=> Add performance logs

src/main/java/com/powsybl/openloadflow/ac/VoltageMagnitudeInitializer.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/JacobianMatrix.java, src/main/java/com/powsybl/openloadflow/equations/Variable.java, src/main/java/com/powsybl/openloadflow/equations/VariableSet.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
No
Refactoring
Opérations on equation terms (scalar multiplication and creation from variable) have been refactored. The API is now more clear with a fluent style API.
=> Refactor equation term operations

pom.xml, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationType.java
No
feature
We use core 4.6.0 RC1
We use core 4.6.0 …
=> PowSyBl Core 4.6.0

src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractFictitiousLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/OperationalLimitsTest.java
No
Design issue
`LfLimit` is in `AbstractLfBranch`
`LfLimit` is moved to API side so  in `LfBranch`
(if any of …
=> Move LfLimit to LfBranch

src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/BusState.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/VoltageControl.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/test/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImplTest.java
=> Fix voltageControlEnabled typo

src/main/java/com/powsybl/openloadflow/network/BusState.java
No.
Voltages are not saved and restored between each contingency.
Voltages are saved and restored.
(if any of the …
=> Fix BusState for security analysis

src/test/java/com/powsybl/openloadflow/ac/SwitchPqPvTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
=> Cleanup security analysis unit tests

pom.xml
=> Prepare release 0.15.0

src/main/java/com/powsybl/openloadflow/ac/outerloop/AcLoadFlowContext.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcTargetVector.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/OperationalLimitsTest.java, src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchWithBreakerIssueTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
No
Refactoring
`AcLoadFlowEngine` has a state.
State of `AcLoadFlowEngine` is moved to `AcLoadFlowContext`
(if …
=> Add AC context

src/main/java/com/powsybl/openloadflow/network/AbstractElement.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java
No
feature
toString() printing the element ID is only implemented for bus.
toString() printing the element ID is implemented for all elements (bus, branch, shunt) …
=> Implements toString() at element level

pom.xml
=>  Prepare release 0.16.0

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/ac/AbstractTransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/DefaultOuterLoopConfig.java, src/main/java/com/powsybl/openloadflow/ac/SimpleTransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/TransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerControlTest.java, src/test/resources/debug-parameters.json
=> First try for a second transformer voltage control outerloop mode

src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
No
Bug fix
Even in DC mode, we have an error message saying there is no PV bus.
Error message has been removed in DC mode …
=> Fix spurious PV bus error message in DC mode

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/PiModel.java, src/main/java/com/powsybl/openloadflow/network/PiModelArray.java, src/main/java/com/powsybl/openloadflow/network/SimplePiModel.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
=> DC: fix low impendance branch support

src/main/java/com/powsybl/openloadflow/equations/TargetVector.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfNetworkListener.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkListener.java, src/main/java/com/powsybl/openloadflow/network/PiModel.java, src/main/java/com/powsybl/openloadflow/network/PiModelArray.java, src/main/java/com/powsybl/openloadflow/network/SimplePiModel.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/test/java/com/powsybl/openloadflow/network/impl/LfSwitchTest.java
=> Refactor phase control tap position change event

pom.xml
=> Bump to powsybl-core 4.7.0 RC2

pom.xml
No
feature
It is based on PowSyBl Core 4.7.0 RC2
It is based on PowSyBl Core 4.7.0
(if any of the …
=> Bump PowSyBl Core 4.7.0

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/VoltageMagnitudeInitializer.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystem.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/network/impl/LfSwitchTest.java
No
Bug fix
Min impedance check is done at several places and as it is not the same for AC and DC it can be quite confusing
Everything regarding min impedance check and fix in done inside LfBranch
**Does this PR introduce a …
=> Refactor min impedance detection

README.md, pom.xml
=> Preapre release v0.17.0

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/graph/EvenShiloachGraphDecrementalConnectivityFactory.java, src/main/java/com/powsybl/openloadflow/graph/GraphDecrementalConnectivityFactory.java, src/main/java/com/powsybl/openloadflow/graph/MinimumSpanningTreeGraphDecrementalConnectivityFactory.java, src/main/java/com/powsybl/openloadflow/graph/NaiveGraphDecrementalConnectivityFactory.java, src/main/java/com/powsybl/openloadflow/network/DiscretePhaseControl.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java, src/test/java/com/powsybl/openloadflow/OperationalLimitsTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java, src/test/java/com/powsybl/openloadflow/ac/NonImpedantBranchWithBreakerIssueTest.java, src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java, src/test/java/com/powsybl/openloadflow/network/impl/LfSwitchTest.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
refactoring
Decremental connectivity is created outside of LF network.
Decremental connectivity is attached to LF network to be reusable in different context without performance penalty.
**Does this PR introduce a breaking …
=> Network connectivity refactoring

src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
=> Fix contingency apply for DC sensitivity calculation and reference flows calculation in case of ZERO status

README.md, pom.xml
No
release
0.18.0-SNAPSHOT
0.19.0-SNAPSHOT
=> Prepare release 0.18.0

pom.xml, src/main/java/com/powsybl/openloadflow/OpenLoadFlowReportConstants.java, src/main/java/com/powsybl/openloadflow/ac/DistributedSlackOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/test/resources/debug-parameters.json
No
Adapts logs to the refactoring with TypedValue.
=> Update logs refactoring

pom.xml, src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameterJsonSerializer.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
Signed-off-by: Etienne LESOT <etienne.lesot@rte-france.com>
it implements the modifications of the loadflow provider made in https://github.com/powsybl/powsybl-core/pull/1987
=> refactor loadflow provider from core

README.md, pom.xml
=> Release v0.19.0

.github/workflows/maven.yml, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java, src/test/resources/debug-factors.json
No
Adapt code to new function types available in the core.
On side one of branches was supported implicitely for reference flow.
Both sides of branches are now supported for reference flow.
**Other …
=> New sensitivity function types

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java, src/test/resources/debug-parameters.json
=> Remove Hvdc Ac emulation OpenLoadFlow parameter

src/main/java/com/powsybl/openloadflow/network/impl/Networks.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
=> Bug fix: fix network reset

pom.xml
No
Feature
4.8.0 RC1
4.8.0 RC2 …
=> Use PowSyBl Core 4.8.0 RC2

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcLoadFlowContext.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java
=> Bug: AC sensitivity analysis with a phase shifter active power control on

src/main/java/com/powsybl/openloadflow/network/LfContingency.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java
No
Renaming
Not clear which buses and branches are stored in LfContingency
Buses and branches stored in LfContingency are renamed disabledBuses and disabledBranches for clarification
=> Clarify buses and branches stored in LfContingency

src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java
- Remove duplicated code.
- Remove connectivity computation that is already stored in the `LfContingency`.
(if any of the …
=> AC sensitivity analysis: refactoring

pom.xml
No
feature
Core 4.8.0-RC2
Core 4.8.0 …
=> Use PowSyBl Core 4.8.0

src/main/java/com/powsybl/openloadflow/network/NetworkState.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
No
Cleanup
Some SA logs are info but often useless
These logs have been downgraded to trace
(if any of the …
=> Clean security analysis logs

pom.xml
=> Prepare release v0.20.0

src/main/java/com/powsybl/openloadflow/ac/TransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/AbstractElement.java, src/main/java/com/powsybl/openloadflow/network/AbstractPropertyBag.java, src/main/java/com/powsybl/openloadflow/network/LfElement.java, src/main/java/com/powsybl/openloadflow/network/LfGenerator.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/PropertyBag.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/test/java/com/powsybl/openloadflow/network/PropertyTest.java
No
Refactoring
Untyped data storable in network model are named user object
It is now named property
(if any …
=> Rename user object to property

src/main/java/com/powsybl/openloadflow/ac/AbstractTransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/PhaseControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/ShuntVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/TransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/OuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/OuterLoopContext.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/OuterLoopContextImpl.java
No
feature
An `OuterLoopContext` instance is recreated at each iteration. 
Same `OuterLoopContext` is reused for all iterations allowing to store contextual data. …
=> Outer loops persistent context

.github/workflows/maven.yml, pom.xml, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java, src/test/resources/debug-network.xiidm
No
Update for powsybl-core PR powsybl/powsybl-core#2062
=> Update platform config changes

pom.xml, src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java
Signed-off-by: Etienne LESOT <etienne.lesot@rte-france.com>
feature
It implements new method from powsybl core loadflow provider to update specific parameters
=> implements update of specific parameters

src/main/java/com/powsybl/openloadflow/network/LfHvdc.java, src/main/java/com/powsybl/openloadflow/network/LfVscConverterStation.java, src/main/java/com/powsybl/openloadflow/network/impl/LfHvdcImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java
No
Design issue
`LfHvdc` depends on `LfVscConverterStationImpl` which belongs to impl package.
`LfVscConverterStation` has been added. …
=> Fix LfVscConverterStationImpl design

src/test/java/com/powsybl/openloadflow/ac/AcEquationsTest.java
No
Better testing
There is no individual unit test for equation term sensi value calculation
There is
(if any …
=> Add unit test for sensi value non regression

pom.xml
No
Feature
We use core 4.9.0-RC1
We use core 4.9.0 and other dependencies have been updated
(if any of the …
=> Use PowSyBl Core 4.9.0

pom.xml
=> Prepare release v0.21.0

.github/workflows/maven.yml
No
Bug fix
We cannot get SonarCloud report in the PR, because of a breaking change on SonarCloud side.
It works again
**Other …
=> Workflow trigger updated

src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/LimitViolationManager.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
=> Limit violations refactoring

src/main/java/com/powsybl/openloadflow/network/impl/ContingencyTripping.java, src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No. 
We support a three windings transformer contingency and the loose of a three windings transformer by contingency propagation, for security and sensitivity analyses. …
=> Support of three windings transformer contingency

src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java, src/main/java/com/powsybl/openloadflow/network/NameSlackBusSelector.java, src/main/java/com/powsybl/openloadflow/network/NetworkSlackBusSelector.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/network/NameSlackBusSelectorTest.java
=> Select slack bus from a voltage level ID

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/DistributedSlackOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/main/java/com/powsybl/openloadflow/util/Reports.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/resources/esgTutoReport.txt
=> Functional logging refactoring

src/main/java/com/powsybl/openloadflow/network/SimplePiModel.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java
=> Fix FastMath dependency

README.md, pom.xml
=> Prepare release v0.22.0

.github/workflows/maven.yml, pom.xml, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
=> Upgrade to powsybl core 4.10.0-alpha-1

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractShuntCompensatorEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystem.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ShuntCompensatorActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ShuntCompensatorReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/network/AdmittanceShift.java, src/main/java/com/powsybl/openloadflow/network/BusState.java, src/main/java/com/powsybl/openloadflow/network/LfContingency.java, src/main/java/com/powsybl/openloadflow/network/LfShunt.java, src/main/java/com/powsybl/openloadflow/network/impl/LfShuntImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowShuntTest.java
No
This PR models the G component of shunt
Currently G component of shunts is not taken into account, as if G always equals 0
The new behavior takes G values of shunt into account
No
=> Model shunt g component

pom.xml, src/main/java/com/powsybl/openloadflow/graph/AbstractGraphConnectivity.java, src/test/java/com/powsybl/openloadflow/graph/ConnectivityTest.java, src/test/java/com/powsybl/openloadflow/graph/NetworkConnectivityTest.java
No
Feature
When we add or remove the same edge in a connectivity graph we had en exception because:
- it has been explicitly forbidden
- there is a bug in jgrapht 1.4.0 when edges are added multiple times 
Code sample to illustrate the bug in jgrapht 1.4.0
```java
Graph<String, String> …
```
=> Support multiple add and remove of the same edge in connectivity

.github/workflows/maven.yml, pom.xml, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/network/LfNetworkTest.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
Signed-off-by: Etienne LESOT <etienne.lesot@rte-france.com>
powsybl core update
=> Upgrade to powsybl-core 4.10.0-RC1

pom.xml
No
Cleanup
We override jgrapht version
We use core version of jgrapht
(if any of the questions/checkboxes …
=> Use JGrapht version of core

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisTest.java
=> Sensitivity analysis: support of dangling line as function reference (active flow and current)

pom.xml, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
=> Update PowSyBl Core to 4.10.0

README.md, pom.xml
=> Prepare release 0.23.0

src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
=> AC sensitivity analysis: fix contingency has no impact

README.md
No
**What kind of change does this PR introduce?** 
docs update
Referencing 0.23.0
Referencing 0.23.1
No
=> Update README.md following 0.23.1 release

src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java
=> Fix bug with optional targetDeadBand

src/main/java/com/powsybl/openloadflow/graph/AbstractGraphConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/GraphConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/ModificationsContext.java, src/test/java/com/powsybl/openloadflow/graph/ConnectivityTest.java
No
Feature
Main component = biggest component
Main component = component with given vertex
No
=> Connectivity: define main component with given vertex

src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/network/LfNetwork.java
No
Bug fix
Even in case of invalid component a log regarding slack bus selection is printed. 
This log is skipped.
**Other …
=> Clean invalid components logging

src/main/java/com/powsybl/openloadflow/network/SimplePiModel.java, src/test/java/com/powsybl/openloadflow/network/SimplePiModelTest.java
No
Bug fix
SimplePiModel.rescaleZ is buggy
SimplePiModel.rescaleZ is correct
=> Fix impedance rescaling 

pom.xml, src/main/java/com/powsybl/openloadflow/ac/nr/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java
No.
- Update to powsybl-core 4.10.1
- Fictitious buses are excluded from unrealistic solution check.
- In case of unrealistic `targetV`, voltage control is not created anymore. …
=> Improvements after IOPs

src/main/java/com/powsybl/openloadflow/network/NameSlackBusSelector.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/network/NameSlackBusSelectorTest.java
=> Use second selector level as fallback selector in NameSlackBusSelector

src/main/java/com/powsybl/openloadflow/ac/ReactiveLimitsOuterLoop.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
=> Bug fix: reactive limits outer loop with voltage remote control

src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Rework DCSecurityAnalysis structure and handle properly statemonitor specific contingency.
Signed-off-by: Bertrand Rix <bertrand.rix@artelys.com>
(if any of the …
=> Rework DC security analysis structure and fix StateMonitor

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoadingReport.java, src/main/java/com/powsybl/openloadflow/util/Reports.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java
=> Revert starting generator fix

src/main/java/com/powsybl/openloadflow/ac/equations/HvdcAcEmulationSide2ActiveFlowEquationTerm.java
No.
Bug fix. The loss factor is totally wrong for equation at side 2. …
=> Fix HVDC AC emulation

src/main/java/com/powsybl/openloadflow/ac/PhaseControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/equations/AbstractClosedBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
No
Refactoring
Some getter have been added to some equation terms to simplify variables access
=> Simplify variable access from equation term

README.md, pom.xml
Prepare next release 0.22.0
0.24.0-SNAPSHOT version
0.24.0 (first commit) then 1.0.0-SNAPSHOT (2nd commit)
=> Prepare release v0.24.0

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java
=> Fix log: generator with inconsistent target

src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java
=> AC sensitivity analysis: add GLSK restoration after loss of connectivity

src/main/java/com/powsybl/openloadflow/ac/AbstractTransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/IncrementalTransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/TransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerControlTest.java
=> Add target dead band check in transformer voltage control outerloop (AFTER_GENERATOR_VOLTAGE_CONTROL)

src/main/java/com/powsybl/openloadflow/ac/outerloop/AcTargetVector.java, src/main/java/com/powsybl/openloadflow/dc/DcTargetVector.java, src/main/java/com/powsybl/openloadflow/equations/Equation.java
No
Code duplication removal
We now have a function in `Equation` to calculate the RHS which is the sum of its terms RHS …
=> Get RHS from equation

src/main/java/com/powsybl/openloadflow/ac/outerloop/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/util/Reports.java
=> Fix calculation status report severity

src/main/java/com/powsybl/openloadflow/network/impl/AbstractImpedantLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBatteryImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBranchImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfBusImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineGenerator.java, src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfSwitch.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/test/java/com/powsybl/openloadflow/network/impl/LfBusImplTest.java
=> Use LfNetworkParameters everywhere to simplify code

src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/network/HvdcState.java, src/main/java/com/powsybl/openloadflow/network/NetworkState.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisContingenciesTest.java
=> Introduce hvdc state save and restore for AC emulation

src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java
=> Fix log message with voltage controllers

src/main/java/com/powsybl/openloadflow/network/impl/LfGeneratorImpl.java
=> Support NaN Droop for slack distribution

src/main/java/com/powsybl/openloadflow/DefaultOuterLoopConfig.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowProviderTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlow3wtTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowBoundaryTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowLccTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowPhaseShifterTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowShuntTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTwoBusNetworkTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowVscTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowWithCachingTest.java, src/test/java/com/powsybl/openloadflow/ac/AcloadFlowReactiveLimitsTest.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java, src/test/java/com/powsybl/openloadflow/ac/IllConditionedCaseTest.java, src/test/java/com/powsybl/openloadflow/ac/MultipleSlackBusesTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
Technical debt
Since we switched to core 5.1.0 RC1, we have a lot a deprecated API usage.
We don't have anymore.
**Other …
=> Fix deprecated API usage

src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystemUpdater.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Support shunt compensator disabling
=> Support shunt compensator disabling

src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java
No
Technical debt
There is a typo in a variable name in sensi analysis.
The type has been fixed.
(if any of …
=> Fix variable name

pom.xml, src/test/resources/debug-network.xiidm
No
Library update
powsybl-core 5.1.0-RC1
powsybl-core 5.1.0
No
=> Bump powsybl-core to 5.1.0

README.md, pom.xml
No
Version update & README.md update
1.0.0-SNAPSHOT version
1. first commit: 1.0.0 version + README.md updated
2. second commit: 1.1.0-SNAPSHOT version
No
=> Prepare 1.0.0 release

src/main/java/com/powsybl/openloadflow/graph/AbstractGraphConnectivity.java, src/main/java/com/powsybl/openloadflow/graph/MinimumSpanningTreeGraphConnectivity.java, src/test/java/com/powsybl/openloadflow/graph/NetworkConnectivityTest.java
No
Technical debt.
We don't use anymore subclasses of `java.lang.Error`. 
=> Remove AssertionError

src/main/java/com/powsybl/openloadflow/ac/IncrementalTransformerVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/ac/PhaseControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/PiModel.java, src/main/java/com/powsybl/openloadflow/network/PiModelArray.java, src/main/java/com/powsybl/openloadflow/network/SimplePiModel.java, src/test/java/com/powsybl/openloadflow/network/PiModelArrayTest.java
No
Refactoring
`PiModelArray` has been refactored to share more code.
=> Refactor PI model array

src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2CurrentMagnitudeEquationTerm.java, src/test/java/com/powsybl/openloadflow/EquationsTest.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
No
Test improvement
We now better test derivative to an unknown variable and DC equations.
=> Improve equations testing

src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2CurrentMagnitudeEquationTerm.java, src/test/java/com/powsybl/openloadflow/EquationsTest.java, src/test/java/com/powsybl/openloadflow/sensi/ac/AcSensitivityAnalysisTest.java
No
Bug fix
i2 derivative with respect to a1 is wrong.
i2 derivative with respect to a1 is correct.
(if any of …
=> Fix i2 derivative to a1

src/main/java/com/powsybl/openloadflow/ac/equations/AbstractClosedBranchAcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide1ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ActiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2CurrentMagnitudeEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/equations/ClosedBranchSide2ReactiveFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/dc/equations/AbstractClosedBranchDcFlowEquationTerm.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/EquationsTest.java, src/test/java/com/powsybl/openloadflow/ac/SecondaryVoltageControlTest.java
No
Bug fix
Even if there is no error in sensi calculation, calculation is not properly done. 
Sensi calculation is better implemented. …
=> Fix sensitivity calculation

src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java
No
Feature
DC context is not closed, in DC security analysis.
DC context is correctly closed.
=> Fix missing DC context close

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/dc/equations/DcEquationSystemCreator.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfNetworkListener.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkListener.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkListenerTracer.java, src/test/resources/logback-test.xml
No
Feature
In trace mode, we can see LF network listener calls.
=> Network listener tracer

src/main/java/com/powsybl/openloadflow/network/LfNetwork.java, src/main/java/com/powsybl/openloadflow/network/LfVscConverterStation.java, src/main/java/com/powsybl/openloadflow/network/impl/LfHvdcImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java
=> Fix hvdc converter stations update for fast restart

src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/sa/LimitViolationManager.java
No
Feature
We lost limit name, which are not added to limit violation.
We now have limit name associated to limit violation. …
=> Add limit name to violation

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
No
Refactoring
Constant for parameters name are not all named in the way. 
All parameters constants ends with PARAM_NAME.
(if any of the questions/checkboxes don't apply, please …
=> Refactor parameters

src/main/java/com/powsybl/openloadflow/ac/outerloop/IncrementalShuntVoltageControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/impl/LfShuntImpl.java
=> Shunt voltage control: fixes after testing on real cases

pom.xml, src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java
No
Feature
Most of the parameters are logs but not all. They are all logged as an invidual line.
A generic processing of parameter is done to automatically log all of them. 
They are formatted as a table for better readability. …
=> Log all parameters formatted as a table

pom.xml, src/test/java/com/powsybl/openloadflow/ac/SecondaryVoltageControlTest.java, src/test/java/com/powsybl/openloadflow/ac/VoltageMagnitudeInitializerTest.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
No
Feature
PowSyBl core 5.2.0 RC1
PowSyBl core 5.2.0
=> Upgrade to PowSyBl Core 5.2.0

README.md, pom.xml
No
Version update & README.md update
1.1.0-SNAPSHOT version
1. first commit: 1.1.0 version + README.md updated
2. second commit: 1.2.0-SNAPSHOT version
No
**DO NOT** squash the commits
=> Prepare 1.1.0 release

pom.xml
No
powsybl-core 5.2.0
powsybl-core 5.2.1
No
=> Bump powsybl-core to 5.2.1

src/main/java/com/powsybl/openloadflow/equations/EquationSystem.java, src/test/java/com/powsybl/openloadflow/equations/EquationSystemTest.java
No
Bug fix
Equation removal is incorrect. Indexed equations by elements is corrupted.
Equation removal is now working correctly.
=> Fix remove equation

src/main/java/com/powsybl/openloadflow/network/LfZeroImpedanceNetwork.java, src/test/java/com/powsybl/openloadflow/ZeroImpedanceFlowsTest.java
=> Fix update voltage control merge status

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java, src/main/java/com/powsybl/openloadflow/network/VoltageControl.java, src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
The `isHidden()` method could means that all the controller elements are disabled. In that case, the target V equation must be deactivated.
Furthermore, there is a mistake in the method to check if a voltage control is hidden or not. The unit test does not show the bug because the defaut behvior on main branch is 'false'. I suggest a more clear version.
=> Fix isHidden() method and add allDisabled() method

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java
No
Bug fix
slackBusesIds parameter type is STRING
slackBusesIds parameter type is STRING_LIST
=> Fix slackBusesIds parameter type

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/test/java/com/powsybl/openloadflow/network/VoltageControlNetworkFactory.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
=> Fix update of voltage controls after bus disabling

pom.xml, src/main/java/com/powsybl/openloadflow/network/impl/ContingencyTripping.java, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java
No
Feature
core 5.3.0 alpha1
core 5.3.0 alpha2
=> Bump powsybl core alpha-2

src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
=> Add unit test for limit violation detection

pom.xml, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
Dependency upgrade
We use core 5.3.0-alpha2
We use core 5.3.0
=> Bump core 5.3.0

README.md, pom.xml
No
Release
Version is 1.2.0-SNAPSHOT
Version is 1.3.0-SNAPSHOT
=> Prepare release 1.2.0

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnLoadTest.java, src/test/java/com/powsybl/openloadflow/network/DistributedSlackNetworkFactory.java
=> Fix power factor constant with conform loads

pom.xml, src/test/java/com/powsybl/openloadflow/network/BoundaryFactory.java
=> Bump to powsybl-core 5.3.2

src/main/java/com/powsybl/openloadflow/NetworkCache.java, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowWithCachingTest.java
No
Bug fix
When transformer voltage control is activated, fast start performance optimization does not work.
=> Fix fast start with transformer voltage control

src/main/java/com/powsybl/openloadflow/network/BusDcState.java, src/main/java/com/powsybl/openloadflow/network/LfAction.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfContingency.java, src/main/java/com/powsybl/openloadflow/network/LfLoad.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLoadImpl.java, src/main/java/com/powsybl/openloadflow/network/util/LoadActivePowerDistributionStep.java, src/test/java/com/powsybl/openloadflow/network/OriginalIdsTest.java
=> LfLoad refactoring

src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowContext.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java
No
Refactoring
We don't use `DcLoadFlowContext` in DC sensi
We use `DcLoadFlowContext` in DC sensi
=> Use DC context in DC sensi

src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/sensi/dc/DcSensitivityAnalysisContingenciesTest.java
No
Feature
From a sensi replay, we can only get sensi values.
We also get contingencies and factors.
=> Improve sensi replay results

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisReportTest.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisContingenciesTest.java, src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisTest.java
No
Refactoring
Sensi test package does not reflect prod package and oblige to have some bad method/class visibility.
dc and ac sub packages have been removed and all visibility modifiers have been fixed.
=> Refactor sensi test package

.github/workflows/maven.yml, .gitignore, .mvn/wrapper/maven-wrapper.properties, README.md, mvnw, mvnw.cmd
No
Feature
powsybl-core needs an installed Maven distribution to be compiled.
powsybl-core can be compiled using Maven Wrapper.
No
=> Add Maven Wrapper

src/main/java/com/powsybl/openloadflow/network/impl/LfDanglingLineBranch.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No.
Side 1 for network side, side 2 for boundary side.
=> Support of BranchResult for dangling line

pom.xml, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/network/BoundaryFactory.java, src/test/resources/debug-network.xiidm
No
Feature
PowSyBl core 5.3.2
PowSyBl core 6.0.0 RC1
=> Upgrade to PowSyBl core 6.0.0-RC1

pom.xml
=> Bump to powsybl-parent 15

src/test/java/com/powsybl/openloadflow/Ieee14Test.java
No
Feature
A full IEEE 14 unit test has been added with assertion on voltages. Test is done on AC and DC model and taking into account or not the transformers ratio in DC mode.
=> Add a IEEE 14 unit test

README.md, pom.xml
No
Version update & README.md update
1.3.0-SNAPSHOT version
1. first commit: 1.3.0 version + README.md updated
2. second commit: 1.4.0-SNAPSHOT version
No
**DO NOT** squash the commits
=> Prepare 1.3.0 release

src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfGenerator.java, src/test/java/com/powsybl/openloadflow/ac/DistributedSlackOnGenerationTest.java
=> Exclude generators below zero or negative minP from slack distribution

pom.xml
No.
Bump to core 6.0.1 to be able to remove a voltage angle limit.
=> Bump to core version 6.0.1

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisTest.java
No
Bug fix
When running a sensi analysis using an HVDC as a variable for the factor, if the hvdc is disconnected we get a NPE. 
Sensi is correctly calculated.
=> Fix sensi on disconnected HVDC

src/main/java/com/powsybl/openloadflow/network/LfNetworkParameters.java, src/main/java/com/powsybl/openloadflow/network/impl/HvdcConverterStations.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLoadImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/LfVscConverterStationImpl.java, src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingencyCreationParameters.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sa/DcSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java, src/test/java/com/powsybl/openloadflow/sa/LfActionTest.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisGraphTest.java, src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisTest.java
No
Refactoring
Propagated contingency API is badly designed because we need 2 phases, one to create and another one to complete the data knowing the breaker mode.
We don't need anymore the breaker mode and we can remove the complete phase.
=> Refactor propagated contingency

src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java
No
Performance improvement.
There is too many network equipment lookup, which with a huge number of factors is responsible from performance issue.
We cache equipments.
=> Improve factors read performance

src/main/java/com/powsybl/openloadflow/sa/LimitViolationManager.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
Bug fix
When during a security analysis, there is multiple bus voltage violation for just one voltage level, we only report one violation.
We report as many violation as there is.
=> Fix missing voltage limit violations

pom.xml
No
Lib update
powsybl-core 6.0.1
powsybl-core 6.0.2
=> Bump powsybl-core to 6.0.2

README.md, pom.xml
Prepare next release 1.4.0
1.4.0-SNAPSHOT version
1.4.0 and README.md updated (first commit) then 1.5.0-SNAPSHOT (2nd commit)
:warning: **DO NOT** squash the commits
:warning: Merge branch on main with fast-forward locally, then push, in order to keep the commits verified
=> Prepare v1.4.0 release

src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java
No.
I think we have useless lines of code... 
=> Clean AC Equation System

src/main/java/com/powsybl/openloadflow/network/impl/extensions/SubstationAutomationSystemsSerDe.java
No
Bug fix
JSON deserializing fails
JSON deserializing succeeds
No
=> Fix SubstationAutomationSystems deserializer

src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
No
Bug fix
The limit violation for the permanent limit is created without any name.
The limit violation for the permanent limit is named "Permanent limit".
=> Add a name to permanent limit violation

src/main/java/com/powsybl/openloadflow/ac/AcTargetVector.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemCreator.java, src/main/java/com/powsybl/openloadflow/ac/equations/AcEquationSystemUpdater.java, src/main/java/com/powsybl/openloadflow/ac/equations/asym/AsymmetricalAcEquationSystemCreator.java, src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java, src/main/java/com/powsybl/openloadflow/network/AbstractLfNetworkListener.java, src/main/java/com/powsybl/openloadflow/network/BusState.java, src/main/java/com/powsybl/openloadflow/network/GeneratorReactivePowerControl.java, src/main/java/com/powsybl/openloadflow/network/LfBranch.java, src/main/java/com/powsybl/openloadflow/network/LfBus.java, src/main/java/com/powsybl/openloadflow/network/LfContingency.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkListener.java, src/main/java/com/powsybl/openloadflow/network/LfNetworkListenerTracer.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBranch.java, src/main/java/com/powsybl/openloadflow/network/impl/AbstractLfBus.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java
=> Refactor reactive power control

src/main/java/com/powsybl/openloadflow/network/AdmittanceShift.java, src/main/java/com/powsybl/openloadflow/network/LfLostLoad.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLoadImpl.java, src/main/java/com/powsybl/openloadflow/sa/AcSecurityAnalysis.java
No
Bug fix
The contingency impact log on the AC security analysis is ugly.
We print all necessary information of the contingency impact.
=> Clean security analysis contingency impact log

src/test/java/com/powsybl/openloadflow/graph/ConnectivityTest.java
No
Connectivity unit tests design bug
Each test is calling the same method with different arguments
Each test is parameterized
=> Parameterized connectivity unit tests

src/main/java/com/powsybl/openloadflow/ac/equations/OpenBranchSide2CurrentMagnitudeEquationTerm.java
No
Bug fix.
For an open branch side 2 with a variable ratio, the equation is not correct.
The equation has been fixed.
=> Fix OpenBranchSide2CurrentMagnitudeEquationTerm

README.md, pom.xml
Prepare next release 1.5.0
1.5.0-SNAPSHOT version
1.5.0 and README.md updated (first commit) then 1.6.0-SNAPSHOT (2nd commit)
:warning: **DO NOT** squash the commits
:warning: Merge branch on main with fast-forward locally, then push, in order to keep the commits verified
=> Prepare v1.5.0 release

README.md, pom.xml
Prepare next release 1.6.0
1.6.0-SNAPSHOT version
1.6.0, bump powsybl-core to 6.1.1 and README.md updated (first commit) then 1.7.0-SNAPSHOT (2nd commit)
:warning: **DO NOT** squash the commits
:warning: Merge branch on main with fast-forward locally, then push, in order to keep the commits verified
=>  Prepare v1.6.0 release

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java, src/test/java/com/powsybl/openloadflow/network/MostMeshedSlackBusSelectorTest.java
=> Consistency checks for input OLF parameters

.github/workflows/maven.yml
No
Bug fix
CI failed at source checkout
We upgrade to newer a action version.
=> Update GH actions versions

src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java, src/test/java/com/powsybl/openloadflow/OpenLoadFlowParametersTest.java
No
Bugfix
missing OLF Specific Parameters in equals and clone
all OLF Specific Parameters in equals and clone + hopefully won't happen ever again with new automated test
=> Fix OpenLoadFlowParameters equals and clone

README.md, pom.xml
No
Feature
we use powsybl-core:6.2.0-RC1
we use powsybl-core:6.2.0
=> Bump to powsybl-core 6.2.0

README.md, pom.xml
Prepare next release 1.7.0
1.7.0-SNAPSHOT version
1.7.0 and README.md updated (first commit) then 1.8.0-SNAPSHOT (2nd commit)
⚠️ **DO NOT** squash the commits
⚠️ Merge branch on main with fast-forward locally, then push, in order to keep the commits verified
=> Prepare v1.7.0 release

src/main/java/com/powsybl/openloadflow/network/impl/LfStaticVarCompensatorImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowSvcTest.java
No
Bugfix
Under certain condition an SVC slope might be ignored while it shouldn't.
With following options:
- voltagePerReactivePowerControl true
- svcVoltageMonitoring **false**
And an SVC with:
- VoltagePerReactivePowerControl extension defined (slope)
- StandbyAutomaton extension **not** defined
In this case an incorrect warning is raised and the slope not simulated.
`Static var compensator <id> has VoltagePerReactivePowerControl and StandbyAutomaton extensions, VoltagePerReactivePowerControl extension ignored`
SVC slope simulated …
=> Fix Static Var Compensator slope not simulated

src/main/java/com/powsybl/openloadflow/ac/solver/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/network/impl/LfLegBranch.java
Typo fix
Logger is missing a ")"
Logger will have a ")"
=> Fix logger typo

README.md, pom.xml
- [ x] The commit message follows our guidelines
Prepare next release 1.8.0
1.8.0-SNAPSHOT version
1.8.0 then 1.9.0-SNAPSHOT (2nd commit) then readme updated.
DO NOT squash the commits
=> Prepare release 1.8.0

src/main/java/com/powsybl/openloadflow/ac/solver/NewtonRaphson.java, src/main/java/com/powsybl/openloadflow/util/Reports.java, src/test/resources/detailedNrReportSecurityAnalysis.txt, src/test/resources/esgTutoReportDetailedNrReportLf.txt, src/test/resources/esgTutoReportDetailedNrReportSensi.txt, src/test/resources/shuntVoltageControlOuterLoopReport.txt, src/test/resources/transformerReactivePowerControlOuterLoopReport.txt
Bug fix
Currently reported NR mismatches are unitless
Add units for reported NR mismatches
=> NR mismatch reporter: add unit in mismatches

src/main/java/com/powsybl/openloadflow/network/impl/LfBatteryImpl.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowBatteryTest.java
No.
Support of voltage regulation for battery through an extension from `powsybl-core` 6.3.0.
=> Support of VoltageRegulation extension for Battery

src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java, src/main/java/com/powsybl/openloadflow/equations/InjectionDerivable.java, src/main/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/main/java/com/powsybl/openloadflow/util/Derivable.java, src/test/java/com/powsybl/openloadflow/equations/DerivableTest.java, src/test/java/com/powsybl/openloadflow/sensi/AbstractSensitivityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisTest.java
- [ X] The commit message follows our guidelines
- [ X] Tests for the changes have been added (for bug fixes / features)
Fixes #989
- [ X] Yes  -> Needs a new enum in the sensitivity-analysis  API
=> Sensistivity analysis: support sensitivity of reactive injection to a voltage setpoint

README.md, pom.xml
Prepare next release 1.9.0
1.9.0-SNAPSHOT version
1.9.0 then 1.10.0-SNAPSHOT (2nd commit) then readme updated.
DO NOT squash the commits
=> Prepare release 1.9.0

src/main/java/com/powsybl/openloadflow/network/impl/PropagatedContingency.java, src/test/java/com/powsybl/openloadflow/sa/LfContingencyTest.java
=> add Battery case for getIdentifiable for Propagated Contingency

src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/main/java/com/powsybl/openloadflow/util/Reports.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java, src/test/resources/saReportOperatorStrategies.txt
#807 
Bugfix
reports from the actions applications are not properly named and separated from the post contingency part.
Reports from the action application properly separated from the post contingency report.
=> Add operator strategy simulation report node

pom.xml
=> Prepare release v1.10.0

README.md, pom.xml
No
Release
1.11.0-SNAPSHOT
1.12.0-SNAPSHOT
=> Prepare release v1.11.0

pom.xml
=> Bump to core 6.4.0

README.md, pom.xml
Release
1.12.0-SNAPSHOT version
1.12.0 then 1.13.0-SNAPSHOT (2nd commit) + readme updated.
:warning: DO NOT squash the commits
=> Prepare release v1.12.0

src/main/java/com/powsybl/openloadflow/dc/ComputedContingencyElement.java, src/main/java/com/powsybl/openloadflow/sensi/ComputedContingencyElement.java, src/main/java/com/powsybl/openloadflow/sensi/ConnectivityBreakAnalysis.java, src/main/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysis.java, src/test/java/com/powsybl/openloadflow/sensi/DcSensitivityAnalysisTest.java
The connectivity break analysis and the ComputedContingencyElement class are extracted from the DC sensitivityAnalysis.
Everything is in the class DcSensitivityAnalysis.
Three classes are defined.
=> Extract ConnectivityBreakAnalysis and ComputedContingencyElement from DcSensitivityAnalysis

src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java
No.
We display now the voltage magnitude at controlled bus and not at controller bus.
=> Fix log for switching PQ to PV

docs/security/security.md, src/main/java/com/powsybl/openloadflow/network/LfAction.java, src/main/java/com/powsybl/openloadflow/sa/AbstractSecurityAnalysis.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java
Yes : https://github.com/powsybl/powsybl-open-loadflow/issues/948
Security analysis simulation is now runned on all components of the network. Results are merged.
Security analysis was only runned on largest component.
=> Security analysis: run simulation on all components

pom.xml
No
Uses powsybl-core 6.5.0-RC1.
Uses powsybl-core **6.5.0**.
=> Bump core to 6.5.0

README.md, pom.xml
Release
1.13.0-SNAPSHOT version
1.13.0 then 1.14.0-SNAPSHOT (2nd commit) + readme updated.
:warning: DO NOT squash the commits
=> Prepare release v1.13.0

README.md
No
Documentation update
Last OLF version in `README.md` is `1.13.0`.
Last OLF version in `README.md` is `1.13.1`.
=> Update OLF version in README: v1.13.1

README.md, pom.xml
No
Uses powsybl-core 6.5.0.
Uses powsybl-core **6.5.1**.
=> Bump powsybl-core to 6.5.1

README.md
No
Documentation update
Last OLF version in `README.md` is `1.13.1`.
Last OLF version in `README.md` is `1.13.2`.
=> Update OLF version in README: v1.13.2

pom.xml
Upgrade pom parent version.
Updates build configuration.
No change expected. Just keep up to date with powsybl build chain and configuration.
=> bump parent pom to version 20

src/main/java/com/powsybl/openloadflow/NetworkCache.java
No
Adaptation to powsybl-core changes
powsybl/powsybl-core#3203 introduces changes in the `NetworkListener` interface. `NetworkCache.Entry` implements the old interface.
`NetworkCache.Entry` implements the modified interface.
=> Adapt to new NetworkListener methods

pom.xml, src/main/java/com/powsybl/openloadflow/NetworkCache.java
No
powsybl-core 6.5.1
powsybl-core 6.6.0-RC1
=> Bump powsybl-core to v6.6.0-RC1

pom.xml
No
Uses powsybl-core 6.6.0-RC1.
Uses powsybl-core **6.6.0**.
=> Bump powsybl-core to 6.6.0

src/main/java/com/powsybl/openloadflow/ac/equations/asym/LoadFortescuePowerEquationTerm.java, src/main/java/com/powsybl/openloadflow/network/DisabledBranchStatus.java, src/main/java/com/powsybl/openloadflow/network/ReactivePowerControl.java, src/main/java/com/powsybl/openloadflow/network/TransformerReactivePowerControl.java
No
Quality
Javadoc build warnings when `mvn javadoc:javadoc`
No javadoc warnings
=> Fix javadoc warnings

README.md
No
Documentation update
Last OLF version in README.md is `1.14.0`.
Last OLF version in README.md is `1.14.1`.
=> Update OLF version in README: v1.14.1

.gitignore, README.md, docs/README.md
Improve README adding the "Build the documentation" section.  
Now the documentation should be built in the docs/_build folder with the `make` or `sphinx` commands.
=> Add "Build the doc" section in the readme

docs/sensitivity/sensitivity.md
Doc update, PROPORTIONAL_TO_GENERATION_P was not mentionned in documentation but is supported in the code for sensitivity analysis.
=> Doc update: PROPORTIONAL_TO_GENERATION_P distribution type is supported in sensitivity analysis

src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java, src/test/java/com/powsybl/openloadflow/ac/SwitchPqPvTest.java
- [X ] The commit message follows our guidelines
The PQ switch report fails when several buses switch PV to PQ
This PR fixes the isse and adds unit tests
=> fix pq switch report

pom.xml
=> Bump powsybl-core to 6.7.0

README.md, pom.xml
Release
1.15.0-SNAPSHOT version
1.15.0 then 1.16.0-SNAPSHOT (2nd commit) + readme updated.
**⚠️ DO NOT squash the commits
Merge branch on main with fast-forward locally, then push, in order to keep the commits verified**
=> Prepare release 1.15.0

README.md, pom.xml
No
Uses powsybl-core 6.7.0.
Uses powsybl-core **6.7.1**.
=> Bump powsybl-core to v6.7.1

README.md
No
Documentation update
Last OLF version in README.md is 1.15.0.
Last OLF version in README.md is 1.15.1.
=> Update OLF version in README: v1.15.1

README.md, pom.xml
Prepare release 1.15.2
that bumps powsybl-core to 6.7.2
=> DO NOTE MERGE - prepare release 1.15.2

src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowEurostagTutorialExample1Test.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowReportTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowShuntTest.java, src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlTest.java, src/test/java/com/powsybl/openloadflow/ac/GeneratorTargetVoltageInconsistencyTest.java, src/test/java/com/powsybl/openloadflow/ac/SecondaryVoltageControlTest.java, src/test/java/com/powsybl/openloadflow/ac/SwitchPqPvTest.java, src/test/java/com/powsybl/openloadflow/dc/DcLoadFlowTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisTest.java, src/test/java/com/powsybl/openloadflow/sa/OpenSecurityAnalysisWithActionsTest.java, src/test/java/com/powsybl/openloadflow/sensi/AcSensitivityAnalysisReportTest.java, src/test/java/com/powsybl/openloadflow/util/ReportsTest.java
No
Adapt the class name to get the correct tests resources bundle reference (due to class renaming in core)
=> Rename test resources bundle

pom.xml
No
Uses powsybl-core 6.8.0-RC2
Uses powsybl-core 6.8.0
=> Bump powsybl-core to v6.8.0

README.md, pom.xml
No
Release PR
OLF is in v1.16.0-SNAPSHOT
1st commit : OLF is in v1.16.0
2nd commit : OLF is in v1.17.0-SNAPSHOT
(README updated)
⚠️ DO NOT squash the commits
=> Prepare release v1.16.0

pom.xml, src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java, src/main/java/com/powsybl/openloadflow/ac/equations/asym/LoadFortescuePowerEquationTerm.java, src/main/java/com/powsybl/openloadflow/ac/solver/NewtonRaphsonFactory.java, src/main/java/com/powsybl/openloadflow/dc/DcAreaInterchangeControlOuterLoop.java, src/main/java/com/powsybl/openloadflow/dc/DcLoadFlowEngine.java, src/main/java/com/powsybl/openloadflow/graph/BridgesFinder.java, src/main/java/com/powsybl/openloadflow/network/BusState.java, src/main/java/com/powsybl/openloadflow/network/impl/LfNetworkLoaderImpl.java, src/main/java/com/powsybl/openloadflow/network/util/ActivePowerDistribution.java
…ctature and adds more pedantic rules
No
Allow use of new Java 21 syntax 
and enforce some random other new rules that come with...
Check style fails if you use java 21 specific syntaxes
You shoud be able to use java 21 specific syntaxes if your white-space placement is agreed by checkstyle among other things.
=> Bump powsybl-parent to 24 and apply new checkstyle rules

pom.xml, src/main/java/com/powsybl/openloadflow/OpenLoadFlowProvider.java, src/main/java/com/powsybl/openloadflow/sensi/OpenSensitivityAnalysisProvider.java
No
Uses powsybl-core 6.8.1.
- Uses **powsybl-core 7.0.0-RC1**
- Is compliant with the new load flow and sensitivity analysis APIs
=> Bump to powsybl-core 7.0.0-RC1 + new load flow and sensitivity APIs support
